import PSTSEPPA.PSTS.CayleyContentConditionalPSTSTheorem
import Mathlib.Data.Fintype.Basic
import Mathlib.Data.Fintype.Pi
import Mathlib.Data.Fintype.Option

/-!
# The complete selected alphabet of a finite PSTS is itself finite

For the final Cayley-GRL application, selecting ALL partial
automorphisms is not enough; the positive edge alphabet E=Q×P
of the oriented Cayley graph must also be FINITE.

There is a straightforward injective forgetful map from the
partial automorphisms of a PSTS to the option-valued partial
maps V → Option V. For finite V, this function type is finite.
The closed-source, closed-target, and operation-compatibility
proof fields of PartialAut are propositions, so equality of
the underlying partial maps implies equality of PartialAut.

This supplies a concrete Fintype instance for all partial
PSTS automorphisms and hence the finite positive Cayley edge
alphabet used in the final finite group-reflection theorem.
No finite enumeration is assumed and no new axioms are used.
-/

namespace PSTSEPPA
namespace PSTS

variable {V : Type*}

/-- The type of all partial automorphisms of a finite PSTS is
finite, by injection into the finite function type of partial
maps on the original vertex set. -/
theorem partialAut_finite [Fintype V] (A : PSTS V) :
    Finite (PartialAut A) := by
  classical
  let f : PartialAut A → (V → Option V) :=
    fun p x => p.toPEquiv x
  have hf : Function.Injective f := by
    intro p q hpq
    apply PartialAut.ext
    apply PEquiv.ext
    intro x
    exact congrFun hpq x
  exact Finite.of_injective f hf

/-- The canonical finite generator alphabet P=PartialAut A.
This is the precise finite alphabet required for the
specialised finite Cayley graph Q×P. -/
noncomputable instance [Fintype V] (A : PSTS V) :
    Fintype (PartialAut A) := by
  classical
  letI : Finite (PartialAut A) := partialAut_finite A
  exact Fintype.ofFinite _

/-- Consequently the oriented POSITIVE edges of the Cayley
graph on Q generated by all selected PSTS automorphisms
form a finite type. -/
noncomputable instance [Fintype V] (A : PSTS V) :
    Fintype ((allPartialAutPermutationLifts A).generatedQ × PartialAut A) := by
  classical
  infer_instance

end PSTS
end PSTSEPPA
