import PSTSEPPA.PSTS.CayleyPairwiseReductionToMax
import Mathlib.Data.Finset.Erase
import Mathlib.Data.Finset.Card

/-!
# Single-edge Cayley path deletion implies the full content-reflection interface

The hard part of the source ABO I Lemma 5.6 is LOCAL: if a path u uses
a positive edge e, but another word v with the same reflecting-group
value omits e, one can replace u by a path w of the SAME value
whose positive support is contained in support(u) with e removed.
The endpoints in the Cayley Q-graph are preserved by the explicit
homomorphism from H to Q, already included in this interface.

This module proves the FINITE DESCENT implied by that local lemma.
Among words representing the fixed H-value and supported within
support(u), choose one with as few edges outside support(v) as possible.
Any remaining outside edge could be removed by the local lemma,
contradicting minimality. Hence the chosen word is supported in
support(u) INTERSECT support(v).

Thus a ONE-EDGE path-reflection theorem suffices for the earlier
pairwise-content certificate, fibre-MAX, and finite PSTS EPPA.
The hard existence of a finite reflecting group with that deletion
property is deliberately NOT assumed as a Lean axiom or proved here.

The converse pairwise => one-edge property is also established, so
the two interfaces are equivalent for a fixed finite H and lifts.
The formulation is source-facing and isolates the constructive
content of corrected ABO Lemma 5.6/Corollary 5.7.
-/

namespace PSTSEPPA
namespace PSTS

variable {V ι : Type*} {A : PSTS V} {gen : ι → PartialAut A}
variable (L : TotalPermutationLifts A gen)

/-- A finite H generated by selected letters, where **one** positive
Cayley edge of a path can be eliminated whenever a competing
same-H-value word omits that edge. The new path must preserve
its exact H-value, and its support must stay within the old support
with the specified edge deleted. -/
structure CayleyOneEdgeContentCertificate where
  H : Type*
  [groupH : Group H]
  [fintypeH : Fintype H]
  lift : ι → H
  toQ : H →* L.generatedQ
  toQ_lift : ∀ i : ι, toQ (lift i) = L.cayleyGenerator i
  word_surjective :
    ∀ h : H, ∃ w : SignedWord ι, SignedWord.evalGroup lift w = h
  delete_one :
    ∀ (u v : SignedWord ι),
      SignedWord.evalGroup lift u = SignedWord.evalGroup lift v →
      ∀ (e : L.generatedQ × ι),
        e ∈ L.finitePositiveSupport u →
        e ∉ L.finitePositiveSupport v →
        ∃ w : SignedWord ι,
          SignedWord.evalGroup lift w = SignedWord.evalGroup lift u ∧
          L.finitePositiveSupport w ⊆
            (L.finitePositiveSupport u).erase e

namespace CayleyOneEdgeContentCertificate

variable {L : TotalPermutationLifts A gen}
variable (C : CayleyOneEdgeContentCertificate L)

instance : Group C.H := C.groupH
instance : Fintype C.H := C.fintypeH

/-- A single-edge deletion theorem implies the pairwise positive
edge-content INTERSECTION property of the original reflecting-path
certificate. The minimization only counts the finite support of
an individual word, and does not require a global finite edge type. -/
theorem pairwise_reduce
    (u v : SignedWord ι)
    (huv : SignedWord.evalGroup C.lift u =
      SignedWord.evalGroup C.lift v) :
    ∃ w : SignedWord ι,
      SignedWord.evalGroup C.lift w = SignedWord.evalGroup C.lift u ∧
      ∀ e : L.generatedQ × ι,
        e ∈ ABO.cayleyWordPositiveTrace L.cayleyGenerator 1 w →
        e ∈ ABO.cayleyWordPositiveTrace L.cayleyGenerator 1 u ∧
        e ∈ ABO.cayleyWordPositiveTrace L.cayleyGenerator 1 v := by
  classical
  let supp : SignedWord ι → Finset (L.generatedQ × ι) :=
    fun w => L.finitePositiveSupport w
  let P : ℕ → Prop := fun n =>
    ∃ w : SignedWord ι,
      SignedWord.evalGroup C.lift w = SignedWord.evalGroup C.lift u ∧
      supp w ⊆ supp u ∧
      (supp w \ supp v).card = n
  have hex : ∃ n : ℕ, P n := by
    refine ⟨(supp u \ supp v).card, u, rfl, ?_, rfl⟩
    exact Subset.rfl
  obtain ⟨w, hwVal, hwSub, hwCard⟩ := Nat.find_spec hex
  refine ⟨w, hwVal, ?_⟩
  intro e heTrace
  have heW : e ∈ supp w :=
    (L.mem_finitePositiveSupport w e).2 heTrace
  have heU : e ∈ supp u := hwSub heW
  by_cases heV : e ∈ supp v
  · exact ⟨(L.mem_finitePositiveSupport u e).1 heU,
      (L.mem_finitePositiveSupport v e).1 heV⟩
  · obtain ⟨w', hw'Val, hw'Erase⟩ :=
      C.delete_one w v (hwVal.trans huv) e heW heV
    have hw'ValU :
        SignedWord.evalGroup C.lift w' =
          SignedWord.evalGroup C.lift u :=
      hw'Val.trans hwVal
    have hw'SubU : supp w' ⊆ supp u := by
      intro x hx
      exact hwSub ((Finset.mem_erase.mp (hw'Erase hx)).2)
    have hForeignSub : (supp w' \ supp v) ⊆ (supp w \ supp v) := by
      intro x hx
      obtain ⟨hxW', hxNotV⟩ := Finset.mem_sdiff.mp hx
      have hxW : x ∈ supp w :=
        (Finset.mem_erase.mp (hw'Erase hxW')).2
      exact Finset.mem_sdiff.mpr ⟨hxW, hxNotV⟩
    have heForeign : e ∈ supp w \ supp v :=
      Finset.mem_sdiff.mpr ⟨heW, heV⟩
    have heNotForeign : e ∉ supp w' \ supp v := by
      intro heWrong
      have heW' : e ∈ supp w' :=
        (Finset.mem_sdiff.mp heWrong).1
      exact (Finset.mem_erase.mp (hw'Erase heW')).1 rfl
    have hProper : (supp w' \ supp v) ⊂ (supp w \ supp v) := by
      apply Finset.ssubset_iff_subset_ne.mpr
      refine ⟨hForeignSub, ?_⟩
      intro heq
      have heWrong : e ∈ supp w' \ supp v := by
        rw [heq]
        exact heForeign
      exact heNotForeign heWrong
    have hCardLt :
        (supp w' \ supp v).card < (supp w \ supp v).card :=
      Finset.card_lt_card hProper
    have hMinimal :
        Nat.find hex ≤ (supp w' \ supp v).card :=
      Nat.find_min' hex ⟨w', hw'ValU, hw'SubU, rfl⟩
    have hContradiction :
        (supp w' \ supp v).card < Nat.find hex := by
      exact lt_of_lt_of_eq hCardLt hwCard
    exact False.elim ((not_lt_of_ge hMinimal) hContradiction)

/-- The one-edge deletion input gives EXACTLY the previously certified
pairwise-reflection certificate, without adding a second hard
group-theoretic assumption. -/
noncomputable def toPairwiseContent :
    CayleyPairwiseContentCertificate L where
  H := C.H
  groupH := C.groupH
  fintypeH := C.fintypeH
  lift := C.lift
  toQ := C.toQ
  toQ_lift := C.toQ_lift
  word_surjective := C.word_surjective
  pairwise_reduce := C.pairwise_reduce

/-- One-edge reflection suffices for the full finite PSTS
fibre-MAX transport interface, through the checked pairwise
content-minimization bridge. -/
noncomputable def toMaxTransporterExtension :
    MaxTransporterExtension A gen :=
  (C.toPairwiseContent).toMaxTransporterExtension

end CayleyOneEdgeContentCertificate

namespace CayleyPairwiseContentCertificate

variable {L : TotalPermutationLifts A gen}
variable (C : CayleyPairwiseContentCertificate L)

/-- Converse: a pairwise reflecting-path certificate deletes any
specified positive edge omitted by a competing same-value word. -/
noncomputable def toOneEdgeContent :
    CayleyOneEdgeContentCertificate L where
  H := C.H
  groupH := C.groupH
  fintypeH := C.fintypeH
  lift := C.lift
  toQ := C.toQ
  toQ_lift := C.toQ_lift
  word_surjective := C.word_surjective
  delete_one := by
    intro u v huv e heU heNotV
    obtain ⟨w, hw, hSupp⟩ := C.pairwise_reduce u v huv
    refine ⟨w, hw, ?_⟩
    intro x hx
    obtain ⟨hxU, hxV⟩ :=
      hSupp x ((L.mem_finitePositiveSupport w x).1 hx)
    have hxNotE : x ≠ e := by
      intro hxe
      subst x
      exact heNotV ((L.mem_finitePositiveSupport v e).2 hxV)
    exact Finset.mem_erase.mpr
      ⟨hxNotE, (L.mem_finitePositiveSupport u x).2 hxU⟩

end CayleyPairwiseContentCertificate
end PSTS
end PSTSEPPA
