import PSTSEPPA.PSTS.CayleyPairwiseReductionToMax
import PSTSEPPA.ABO.CayleySemidirectWordValue
import Mathlib.Data.Fintype.Prod

/-!
# A finite equivariant Cayley reflecting group yields concrete PSTS fibre-MAX

This is the source-exact finite Cayley-GRL -> semidirect-product bridge.

Assume a finite group G with a positive-edge label for each oriented
Cayley edge (q,i), a genuine LEFT Q-translation action on G, and the
pairwise reflecting-path property:
two paths with equal G-value AND the same Cayley endpoint can be
reduced to a path with the same G-value/endpoint and positive-edge
support contained in the INTERSECTION of their supports.

Construct H as the subgroup of G ⋊ Q generated by the actual lifts
h_i=(edge(1,i),genQ(i)). H is finite and every element has a signed
word representative. The already-certified signed semidirect formula
identifies its word value exactly with (pathG(1,w),evalQ(w)).
Thus the Cayley reflecting-path property becomes pairwise reduction
in every H-value fibre. The separate finite-support argument then
produces the exact fibre-MAX needed by the closed-PSTS EPPA transfer.

The reflecting-path property is intentionally a FIELD of the input,
not an axiom and not proved here. Its finite existence is the remaining
hard corrected ABO Section 4/5 theorem.
-/

namespace PSTSEPPA
namespace PSTS

variable {V ι : Type*} {A : PSTS V} {gen : ι → PartialAut A}
variable (L : TotalPermutationLifts A gen)

/-- An actual finite group labelling every positive Cayley edge,
equivariant under LEFT Q-translations, with the one hard pairwise
reflecting-path property required from Cayley-GRL.

Unlike a prepackaged H/minimum-support certificate, this structure
is formulated directly in terms of ABO's G and geometric Cayley paths. -/
structure FiniteEquivariantCayleyReflection where
  G : Type*
  [groupG : Group G]
  [fintypeG : Fintype G]
  action : L.generatedQ →* MulAut G
  edge : L.generatedQ × ι → G
  edge_left :
    ∀ (t q : L.generatedQ) (i : ι),
      action t (edge (q,i)) = edge (t*q,i)
  path_reduce :
    ∀ (u v : SignedWord ι),
      ABO.cayleyPathGroupValue L.cayleyGenerator edge 1 u =
        ABO.cayleyPathGroupValue L.cayleyGenerator edge 1 v →
      SignedWord.evalGroup L.cayleyGenerator u =
        SignedWord.evalGroup L.cayleyGenerator v →
      ∃ w : SignedWord ι,
        ABO.cayleyPathGroupValue L.cayleyGenerator edge 1 w =
          ABO.cayleyPathGroupValue L.cayleyGenerator edge 1 u ∧
        SignedWord.evalGroup L.cayleyGenerator w =
          SignedWord.evalGroup L.cayleyGenerator u ∧
        ∀ e : L.generatedQ × ι,
          e ∈ ABO.cayleyWordPositiveTrace L.cayleyGenerator 1 w →
          e ∈ ABO.cayleyWordPositiveTrace L.cayleyGenerator 1 u ∧
          e ∈ ABO.cayleyWordPositiveTrace L.cayleyGenerator 1 v

namespace FiniteEquivariantCayleyReflection

variable {L : TotalPermutationLifts A gen}
variable (R : FiniteEquivariantCayleyReflection L)

instance : Group R.G := R.groupG
instance : Fintype R.G := R.fintypeG

/-- The true generator h_i=(edge(1,i),genQ(i)) in G ⋊ Q. -/
def semidirectGenerator (i : ι) :
    R.G ⋊[R.action] L.generatedQ :=
  ABO.cayleySemidirectGenerator R.action L.cayleyGenerator R.edge i

/-- The H of the audited transfer is the actual subgroup generated
by the semidirect lifts, not an unproved ambient quotient. -/
def generatedH : Subgroup (R.G ⋊[R.action] L.generatedQ) :=
  Subgroup.closure (Set.range R.semidirectGenerator)

def lift (i : ι) : R.generatedH :=
  ⟨R.semidirectGenerator i, Subgroup.subset_closure ⟨i, rfl⟩⟩

/-- The underlying finite group of G ⋊ Q is in bijection with G×Q. -/
noncomputable instance [Fintype V] :
    Fintype (R.G ⋊[R.action] L.generatedQ) := by
  classical
  exact Fintype.ofEquiv (R.G × L.generatedQ)
    (SemidirectProduct.equivProd).symm

/-- In particular H is finite even if different selected letters
induce the same Q permutation or some are trivial. -/
noncomputable instance [Fintype V] : Fintype R.generatedH := by
  classical
  exact Fintype.ofFinite _

/-- Genuine semidirect right projection restricted to H. -/
def toQ : R.generatedH →* L.generatedQ :=
  (SemidirectProduct.rightHom).comp (Subgroup.subtype R.generatedH)

theorem toQ_lift (i : ι) :
    R.toQ (R.lift i) = L.cayleyGenerator i :=
  rfl

/-- Group-word evaluation in H is precisely the restriction
of the same signed-word evaluation in the semidirect product. -/
theorem evalWord_coe (w : SignedWord ι) :
    ((SignedWord.evalGroup R.lift w : R.generatedH) :
      R.G ⋊[R.action] L.generatedQ) =
      SignedWord.evalGroup R.semidirectGenerator w := by
  induction w with
  | nil =>
      rfl
  | cons s w ih =>
      cases s with
      | pos i =>
          change
            R.semidirectGenerator i *
              ((SignedWord.evalGroup R.lift w : R.generatedH) :
                R.G ⋊[R.action] L.generatedQ) =
            R.semidirectGenerator i *
              SignedWord.evalGroup R.semidirectGenerator w
          rw [ih]
      | neg i =>
          change
            (R.semidirectGenerator i)⁻¹ *
              ((SignedWord.evalGroup R.lift w : R.generatedH) :
                R.G ⋊[R.action] L.generatedQ) =
            (R.semidirectGenerator i)⁻¹ *
              SignedWord.evalGroup R.semidirectGenerator w
          rw [ih]

/-- The generators of H really generate every element of H:
signed words suffice, with no assumption that the labelling is
free or injective. -/
theorem exists_word_semidirect
    {g : R.G ⋊[R.action] L.generatedQ}
    (hg : g ∈ R.generatedH) :
    ∃ w : SignedWord ι,
      SignedWord.evalGroup R.semidirectGenerator w = g := by
  change g ∈ Subgroup.closure (Set.range R.semidirectGenerator) at hg
  induction hg using Subgroup.closure_induction with
  | mem x hx =>
      obtain ⟨i, rfl⟩ := hx
      exact ⟨[SignedLetter.pos i], by
        simp [SignedWord.evalGroup]⟩
  | one =>
      exact ⟨[], rfl⟩
  | mul x y hx hy ihx ihy =>
      obtain ⟨u, hu⟩ := ihx
      obtain ⟨v, hv⟩ := ihy
      refine ⟨u ++ v, ?_⟩
      calc
        SignedWord.evalGroup R.semidirectGenerator (u ++ v) =
          SignedWord.evalGroup R.semidirectGenerator u *
            SignedWord.evalGroup R.semidirectGenerator v :=
              SignedWord.evalGroup_append R.semidirectGenerator u v
        _ = x * y := by rw [hu, hv]
  | inv x hx ih =>
      obtain ⟨u, hu⟩ := ih
      refine ⟨SignedWord.inv u, ?_⟩
      calc
        SignedWord.evalGroup R.semidirectGenerator (SignedWord.inv u) =
          (SignedWord.evalGroup R.semidirectGenerator u)⁻¹ :=
            SignedWord.evalGroup_inv R.semidirectGenerator u
        _ = x⁻¹ := congrArg Inv.inv hu

theorem exists_word_H (h : R.generatedH) :
    ∃ w : SignedWord ι, SignedWord.evalGroup R.lift w = h := by
  obtain ⟨w, hw⟩ := R.exists_word_semidirect h.property
  refine ⟨w, ?_⟩
  apply Subtype.ext
  rw [R.evalWord_coe]
  exact hw

/-- Equality of H-word values implies equal G-values of the
actual signed Cayley paths AND equal selected Q-endpoints. -/
theorem wordValue_components
    (u v : SignedWord ι)
    (h : SignedWord.evalGroup R.lift u =
      SignedWord.evalGroup R.lift v) :
    ABO.cayleyPathGroupValue L.cayleyGenerator R.edge 1 u =
      ABO.cayleyPathGroupValue L.cayleyGenerator R.edge 1 v ∧
    SignedWord.evalGroup L.cayleyGenerator u =
      SignedWord.evalGroup L.cayleyGenerator v := by
  have hs :
      SignedWord.evalGroup R.semidirectGenerator u =
      SignedWord.evalGroup R.semidirectGenerator v := by
    calc
      _ = ((SignedWord.evalGroup R.lift u : R.generatedH) :
          R.G ⋊[R.action] L.generatedQ) := (R.evalWord_coe u).symm
      _ = ((SignedWord.evalGroup R.lift v : R.generatedH) :
          R.G ⋊[R.action] L.generatedQ) := congrArg Subtype.val h
      _ = _ := R.evalWord_coe v
  have hpair :
      (⟨ABO.cayleyPathGroupValue L.cayleyGenerator R.edge 1 u,
        SignedWord.evalGroup L.cayleyGenerator u⟩ :
          R.G ⋊[R.action] L.generatedQ) =
      (⟨ABO.cayleyPathGroupValue L.cayleyGenerator R.edge 1 v,
        SignedWord.evalGroup L.cayleyGenerator v⟩ :
          R.G ⋊[R.action] L.generatedQ) := by
    rw [← ABO.cayleySemidirect_wordValue R.action
      L.cayleyGenerator R.edge R.edge_left u,
      ← ABO.cayleySemidirect_wordValue R.action
      L.cayleyGenerator R.edge R.edge_left v]
    exact hs
  exact ⟨congrArg SemidirectProduct.left hpair,
    congrArg SemidirectProduct.right hpair⟩

/-- Actual reflecting-path reduction translates into pairwise
positive-edge content reduction in the H-value fibre. -/
theorem pairwise_H
    (u v : SignedWord ι)
    (h : SignedWord.evalGroup R.lift u =
      SignedWord.evalGroup R.lift v) :
    ∃ w : SignedWord ι,
      SignedWord.evalGroup R.lift w =
        SignedWord.evalGroup R.lift u ∧
      ∀ e : L.generatedQ × ι,
        e ∈ ABO.cayleyWordPositiveTrace L.cayleyGenerator 1 w →
        e ∈ ABO.cayleyWordPositiveTrace L.cayleyGenerator 1 u ∧
        e ∈ ABO.cayleyWordPositiveTrace L.cayleyGenerator 1 v := by
  obtain ⟨hG, hQ⟩ := R.wordValue_components u v h
  obtain ⟨w, hwG, hwQ, htrace⟩ := R.path_reduce u v hG hQ
  refine ⟨w, ?_, htrace⟩
  apply Subtype.ext
  calc
    ((SignedWord.evalGroup R.lift w : R.generatedH) :
        R.G ⋊[R.action] L.generatedQ) =
        SignedWord.evalGroup R.semidirectGenerator w :=
          R.evalWord_coe w
    _ = SignedWord.evalGroup R.semidirectGenerator u := by
      change SignedWord.evalGroup
          (ABO.cayleySemidirectGenerator R.action
            L.cayleyGenerator R.edge) w =
        SignedWord.evalGroup
          (ABO.cayleySemidirectGenerator R.action
            L.cayleyGenerator R.edge) u
      rw [ABO.cayleySemidirect_wordValue R.action
        L.cayleyGenerator R.edge R.edge_left w,
        ABO.cayleySemidirect_wordValue R.action
        L.cayleyGenerator R.edge R.edge_left u]
      exact SemidirectProduct.ext hwG hwQ
    _ = ((SignedWord.evalGroup R.lift u : R.generatedH) :
        R.G ⋊[R.action] L.generatedQ) :=
          (R.evalWord_coe u).symm

/-- The precise finite H input to the already-certified
pairwise-reduction-to-MAX bridge, obtained from a finite G
satisfying the source-facing Cayley reflection property. -/
noncomputable def toPairwiseContent [Fintype V] :
    CayleyPairwiseContentCertificate L where
  H := R.generatedH
  groupH := inferInstance
  fintypeH := inferInstance
  lift := R.lift
  toQ := R.toQ
  toQ_lift := R.toQ_lift
  word_surjective := R.exists_word_H
  pairwise_reduce := R.pairwise_H

/-- Explicit CAYLEY-GRL -> fibre-MAX: no extra H-existence or
global minimum-content assumption is needed. -/
noncomputable def toMaxTransporterExtension [Fintype V] :
    MaxTransporterExtension A gen :=
  (R.toPairwiseContent).toMaxTransporterExtension

end FiniteEquivariantCayleyReflection
end PSTS
end PSTSEPPA
