import PSTSEPPA.PSTS.CayleyMinimalContentToMax
import Mathlib.Data.Nat.Find
import Mathlib.Data.Finset.Card

/-!
# Pairwise Cayley path reduction implies fibre-MAX

The actual reflecting-group input in ABO is naturally a PAIRWISE
reduction statement: any two paths with the same reflecting-group
value admit a third path, still with that value, whose positive
edge content lies in the intersection of their contents.

This file isolates the entirely elementary final step.
Among the words representing a fixed group element choose one
minimising the number of DISTINCT positive Cayley edges.
Pairwise reduction forces the resulting edge support to be
contained in the support of every other representative.

In particular, one need not assume the existence of a canonical
minimal-content word as an additional deep hypothesis: it follows
from pairwise reduction by well-ordering of natural numbers.
Finiteness of the positive alphabet is NOT needed for this step,
since each finite word has a finite edge support.

This file does NOT prove existence of a finite reflecting group
with pairwise reduction. That is the outstanding ABO/Cayley-GRL
theorem.
-/

namespace PSTSEPPA
namespace PSTS

variable {V ι : Type*} {A : PSTS V} {gen : ι → PartialAut A}
variable (L : TotalPermutationLifts A gen)

namespace TotalPermutationLifts

/-- The finite set of positive oriented Cayley edges of a signed
word from identity, including backwards traversal of an edge. -/
noncomputable def finitePositiveSupport (w : SignedWord ι) :
    Finset (L.generatedQ × ι) := by
  classical
  exact ABO.cayleyWordPositiveSupport L.cayleyGenerator 1 w

theorem mem_finitePositiveSupport (w : SignedWord ι)
    (e : L.generatedQ × ι) :
    e ∈ L.finitePositiveSupport w ↔
      e ∈ ABO.cayleyWordPositiveTrace L.cayleyGenerator 1 w := by
  classical
  simp [finitePositiveSupport, ABO.cayleyWordPositiveSupport]

end TotalPermutationLifts

/-- A finite H-value group generated by selected letters, with
a source-exact PAIRWISE reduction property for signed Cayley
paths. No global minimum-content selection is assumed here. -/
structure CayleyPairwiseContentCertificate where
  H : Type*
  [groupH : Group H]
  [fintypeH : Fintype H]
  lift : ι → H
  toQ : H →* L.generatedQ
  toQ_lift : ∀ i : ι, toQ (lift i) = L.cayleyGenerator i
  word_surjective :
    ∀ h : H, ∃ w : SignedWord ι, SignedWord.evalGroup lift w = h
  pairwise_reduce :
    ∀ (u v : SignedWord ι),
      SignedWord.evalGroup lift u = SignedWord.evalGroup lift v →
      ∃ w : SignedWord ι,
        SignedWord.evalGroup lift w = SignedWord.evalGroup lift u ∧
        ∀ e : L.generatedQ × ι,
          e ∈ ABO.cayleyWordPositiveTrace L.cayleyGenerator 1 w →
          e ∈ ABO.cayleyWordPositiveTrace L.cayleyGenerator 1 u ∧
          e ∈ ABO.cayleyWordPositiveTrace L.cayleyGenerator 1 v

namespace CayleyPairwiseContentCertificate

variable {L : TotalPermutationLifts A gen}
variable (C : CayleyPairwiseContentCertificate L)

instance : Group C.H := C.groupH
instance : Fintype C.H := C.fintypeH

theorem exists_support_card (h : C.H) :
    ∃ n : ℕ, ∃ w : SignedWord ι,
      SignedWord.evalGroup C.lift w = h ∧
      (L.finitePositiveSupport w).card = n := by
  obtain ⟨w, hw⟩ := C.word_surjective h
  exact ⟨(L.finitePositiveSupport w).card, w, hw, rfl⟩

/-- A representative with least CARDINALITY of positive-edge
support among all representatives of a prescribed H-value. -/
noncomputable def leastWord (h : C.H) : SignedWord ι := by
  classical
  exact Classical.choose (Nat.find_spec (C.exists_support_card h))

theorem leastWord_spec (h : C.H) :
    SignedWord.evalGroup C.lift (C.leastWord h) = h ∧
    (L.finitePositiveSupport (C.leastWord h)).card =
      Nat.find (C.exists_support_card h) := by
  classical
  exact Classical.choose_spec (Nat.find_spec (C.exists_support_card h))

theorem leastWord_le_card (h : C.H)
    (v : SignedWord ι)
    (hv : SignedWord.evalGroup C.lift v = h) :
    (L.finitePositiveSupport (C.leastWord h)).card ≤
      (L.finitePositiveSupport v).card := by
  classical
  calc
    (L.finitePositiveSupport (C.leastWord h)).card =
        Nat.find (C.exists_support_card h) := (C.leastWord_spec h).2
    _ ≤ (L.finitePositiveSupport v).card :=
        Nat.find_min' (C.exists_support_card h) ⟨v, hv, rfl⟩

/-- The least-cardinality representative's positive edge support
lies inside that of EVERY competing representative, not merely
inside some support of minimum cardinality. This is precisely the
upgrade supplied by pairwise content reduction. -/
theorem leastWord_support_subset (h : C.H)
    (v : SignedWord ι)
    (hv : SignedWord.evalGroup C.lift v = h) :
    L.finitePositiveSupport (C.leastWord h) ⊆
      L.finitePositiveSupport v := by
  obtain ⟨u, hu, hred⟩ :=
    C.pairwise_reduce (C.leastWord h) v
      ((C.leastWord_spec h).1.trans hv.symm)
  have hu' : SignedWord.evalGroup C.lift u = h :=
    hu.trans (C.leastWord_spec h).1
  have hsub : L.finitePositiveSupport u ⊆
      L.finitePositiveSupport (C.leastWord h) := by
    intro e he
    exact (L.mem_finitePositiveSupport (C.leastWord h) e).2
      ((hred e ((L.mem_finitePositiveSupport u e).1 he)).1)
  have hcard : (L.finitePositiveSupport (C.leastWord h)).card ≤
      (L.finitePositiveSupport u).card :=
    C.leastWord_le_card h u hu'
  have heq : L.finitePositiveSupport u =
      L.finitePositiveSupport (C.leastWord h) :=
    Finset.eq_of_subset_of_card_le hsub hcard
  intro e he
  have heu : e ∈ L.finitePositiveSupport u := by
    rw [heq]
    exact he
  exact (L.mem_finitePositiveSupport v e).2
    ((hred e ((L.mem_finitePositiveSupport u e).1 heu)).2)

/-- Pairwise intersection-content reduction yields the exact
finite Cayley minimum-content certificate already known to
imply PSTS fibre-MAX and the constructive closed-EPPA witness. -/
noncomputable def toMinimalContent :
    CayleyMinimalContentCertificate L where
  H := C.H
  groupH := C.groupH
  fintypeH := C.fintypeH
  lift := C.lift
  toQ := C.toQ
  toQ_lift := C.toQ_lift
  minimalWord := C.leastWord
  minimalWord_value := fun h => (C.leastWord_spec h).1
  minimal_support := by
    intro h w hw e he
    exact (L.mem_finitePositiveSupport w e).1
      (C.leastWord_support_subset h w hw
        ((L.mem_finitePositiveSupport (C.leastWord h) e).2 he))

/-- Main payoff: the pairwise Cayley reflection condition gives the
existing mathematically complete finite-PSTS transfer interface. -/
noncomputable def toMaxTransporterExtension :
    MaxTransporterExtension A gen :=
  (C.toMinimalContent).toMaxTransporterExtension

end CayleyPairwiseContentCertificate
end PSTS
end PSTSEPPA
