import PSTSEPPA.PSTS.MaxTransporter
import Mathlib.Data.Quot

/-!
# Quotient development from a maximum transporter extension

The raw points are pairs `(a,g) : V × H`.  The generating glue is

`(a, liftGen i * k) ~ (gen i (a), k)`

whenever the selected partial automorphism `gen i` is defined at `a`.

This file first proves the signed-word transport lemma.  It fixes the
orientation needed later for the equality criterion
`[a,g] = [b,h] ↔ ∃ w, evalH w = g * h⁻¹ ∧ evalM w a = b`.
-/

namespace PSTSEPPA
namespace PSTS

variable {V ι : Type*} {A : PSTS V} {gen : ι → PartialAut A}

/-- Raw points before quotienting by the generator glue. -/
abbrev DevelopmentRaw (X : MaxTransporterExtension A gen) :=
  V × X.H

/-- One positive-generator gluing step. -/
def DevelopmentGlueStep (X : MaxTransporterExtension A gen) :
    DevelopmentRaw X → DevelopmentRaw X → Prop :=
  fun x y =>
    ∃ i a b k,
      (gen i).toPEquiv a = some b ∧
      x = (a, X.liftGen i * k) ∧
      y = (b, k)

/-- Equivalence relation generated by the positive-generator glue. -/
abbrev DevelopmentGlue (X : MaxTransporterExtension A gen) :
    DevelopmentRaw X → DevelopmentRaw X → Prop :=
  Relation.EqvGen (DevelopmentGlueStep X)

namespace MaxTransporterExtension

variable (X : MaxTransporterExtension A gen)

/-- A positive letter gives one generating glue step. -/
theorem glue_pos (i : ι) {a b : V}
    (hab : (gen i).toPEquiv a = some b) (k : X.H) :
    DevelopmentGlue X
      (a, X.liftGen i * k)
      (b, k) := by
  apply Relation.EqvGen.rel
  exact ⟨i, a, b, k, hab, rfl, rfl⟩

/-- A negative letter gives the symmetric generating step. -/
theorem glue_neg (i : ι) {a b : V}
    (hab : (gen i).symm.toPEquiv a = some b) (k : X.H) :
    DevelopmentGlue X
      (a, (X.liftGen i)⁻¹ * k)
      (b, k) := by
  have hinv : (gen i).toPEquiv.symm a = some b := by
    simpa using hab
  have hba : (gen i).toPEquiv b = some a :=
    ((gen i).toPEquiv.eq_some_iff).1 hinv
  have hpos :=
    X.glue_pos i hba ((X.liftGen i)⁻¹ * k)
  have hpos' :
      DevelopmentGlue X
        (b, k)
        (a, (X.liftGen i)⁻¹ * k) := by
    simpa [mul_assoc] using hpos
  exact Relation.EqvGen.symm _ _ hpos'

/-- Any signed letter transports along the corresponding quotient glue. -/
theorem glue_letter (s : SignedLetter ι) {a b : V}
    (hab : (SignedWord.evalLetter gen s).toPEquiv a = some b)
    (k : X.H) :
    DevelopmentGlue X
      (a, SignedWord.evalGroupLetter X.liftGen s * k)
      (b, k) := by
  cases s with
  | pos i =>
      exact X.glue_pos i hab k
  | neg i =>
      exact X.glue_neg i hab k

/-- Fundamental word-glue lemma.

If the partial word maps `a` to `b`, then multiplying the group coordinate
by the group value of the same word gives equivalent raw points. -/
theorem glue_word (w : SignedWord ι) {a b : V}
    (hab : (SignedWord.eval gen w).toPEquiv a = some b)
    (k : X.H) :
    DevelopmentGlue X
      (a, SignedWord.evalGroup X.liftGen w * k)
      (b, k) := by
  induction w generalizing a b k with
  | nil =>
      have hab' : a = b := by
        simpa [SignedWord.eval] using hab
      subst b
      simpa [SignedWord.evalGroup] using
        (Relation.EqvGen.refl (a, k))
  | cons s w ih =>
      have hab' :
          ((SignedWord.evalLetter gen s).toPEquiv.trans
            (SignedWord.eval gen w).toPEquiv) a = some b := by
        simpa [SignedWord.eval] using hab
      rcases (PEquiv.trans_eq_some _ _ _ _).1 hab' with
        ⟨c, hac, hcb⟩
      have h₁ :=
        X.glue_letter s hac
          (SignedWord.evalGroup X.liftGen w * k)
      have h₂ := ih hcb k
      have h₁₂ := Relation.EqvGen.trans _ _ _ h₁ h₂
      simpa [SignedWord.evalGroup, mul_assoc] using h₁₂


/-- Right multiplication on the raw group coordinate. -/
def developmentRawRight (t : X.H) (x : DevelopmentRaw X) :
    DevelopmentRaw X :=
  (x.1, x.2 * t)

/-- One generating glue step is preserved by simultaneous right
multiplication of the group coordinates. -/
theorem glueStep_right
    {x y : DevelopmentRaw X}
    (hxy : DevelopmentGlueStep X x y) (t : X.H) :
    DevelopmentGlueStep X
      (developmentRawRight X t x)
      (developmentRawRight X t y) := by
  rcases hxy with ⟨i, a, b, k, hab, rfl, rfl⟩
  refine ⟨i, a, b, k * t, hab, ?_, ?_⟩
  · simp [developmentRawRight, mul_assoc]
  · rfl

/-- The generated equivalence relation is right-`H` invariant. -/
theorem glue_right
    {x y : DevelopmentRaw X}
    (hxy : DevelopmentGlue X x y) (t : X.H) :
    DevelopmentGlue X
      (developmentRawRight X t x)
      (developmentRawRight X t y) := by
  induction hxy with
  | rel x y hstep =>
      exact Relation.EqvGen.rel _ _ (X.glueStep_right hstep t)
  | refl x =>
      exact Relation.EqvGen.refl _
  | symm x y hxy ih =>
      exact Relation.EqvGen.symm _ _ ih
  | trans x y z hxy hyz ihxy ihyz =>
      exact Relation.EqvGen.trans _ _ _ ihxy ihyz

/-- The concrete signed-word description of a pair of equivalent raw points. -/
def DevelopmentWordWitness
    (x y : DevelopmentRaw X) : Prop :=
  ∃ w : SignedWord ι,
    SignedWord.evalGroup X.liftGen w = x.2 * y.2⁻¹ ∧
    (SignedWord.eval gen w).toPEquiv x.1 = some y.1

/-- Every generated quotient equality is represented by one signed word.

The group coordinate is `x.2 * y.2⁻¹`; this theorem is the orientation
checkpoint for the whole transfer construction. -/
theorem glue_implies_wordWitness
    {x y : DevelopmentRaw X}
    (hxy : DevelopmentGlue X x y) :
    DevelopmentWordWitness X x y := by
  induction hxy with
  | rel x y hstep =>
      rcases hstep with ⟨i, a, b, k, hab, rfl, rfl⟩
      refine ⟨[SignedLetter.pos i], ?_, ?_⟩
      · simp [SignedWord.evalGroup, SignedWord.evalGroupLetter, mul_assoc]
      · simpa [SignedWord.eval, SignedWord.evalLetter] using hab
  | refl x =>
      rcases x with ⟨a, g⟩
      refine ⟨[], ?_, ?_⟩
      · simp
      · simp [SignedWord.eval]
  | symm x y hxy ih =>
      rcases x with ⟨a, g⟩
      rcases y with ⟨b, h⟩
      rcases ih with ⟨w, hwH, hwM⟩
      refine ⟨SignedWord.inv w, ?_, ?_⟩
      · rw [SignedWord.evalGroup_inv, hwH]
        simp
      · rw [SignedWord.eval_inv]
        have hinv :
            (SignedWord.eval gen w).toPEquiv.symm b = some a :=
          ((SignedWord.eval gen w).toPEquiv.eq_some_iff).2 hwM
        simpa using hinv
  | trans x y z hxy hyz ihxy ihyz =>
      rcases x with ⟨a, g⟩
      rcases y with ⟨b, h⟩
      rcases z with ⟨d, k⟩
      rcases ihxy with ⟨u, huH, huM⟩
      rcases ihyz with ⟨v, hvH, hvM⟩
      refine ⟨u ++ v, ?_, ?_⟩
      · rw [SignedWord.evalGroup_append, huH, hvH]
        simp [mul_assoc]
      · rw [SignedWord.eval_append, PartialAut.toPEquiv_trans]
        exact (PEquiv.trans_eq_some _ _ _ _).2 ⟨b, huM, hvM⟩

/-- Conversely, every word witness gives an equality in the generated glue. -/
theorem wordWitness_implies_glue
    {x y : DevelopmentRaw X}
    (hxy : DevelopmentWordWitness X x y) :
    DevelopmentGlue X x y := by
  rcases x with ⟨a, g⟩
  rcases y with ⟨b, h⟩
  rcases hxy with ⟨w, hwH, hwM⟩
  have hglue := X.glue_word w hwM h
  simpa [hwH, mul_assoc] using hglue

/-- Equality criterion for raw representatives.

This is the precise signed-word form used by all later quotient arguments. -/
theorem glue_iff_word
    {a b : V} {g h : X.H} :
    DevelopmentGlue X (a, g) (b, h) ↔
      ∃ w : SignedWord ι,
        SignedWord.evalGroup X.liftGen w = g * h⁻¹ ∧
        (SignedWord.eval gen w).toPEquiv a = some b := by
  constructor
  · intro hab
    exact X.glue_implies_wordWitness hab
  · intro hab
    exact X.wordWitness_implies_glue hab

/-- Setoid generated by the gluing relation. -/
def developmentSetoid :
    Setoid (DevelopmentRaw X) :=
  Relation.EqvGen.setoid (DevelopmentGlueStep X)

/-- Quotient development associated with a MAX extension. -/
def Development :=
  Quotient X.developmentSetoid

/-- Class of a raw pair `(a,g)`. -/
def developmentMk (a : V) (g : X.H) : X.Development :=
  Quotient.mk X.developmentSetoid (a, g)

/-- Right multiplication descends to the quotient development. -/
def developmentRight (q : X.Development) (t : X.H) :
    X.Development :=
  Quotient.map
    (developmentRawRight X t)
    (by
      intro x y hxy
      exact X.glue_right hxy t)
    q

@[simp]
theorem developmentRight_mk (a : V) (g t : X.H) :
    X.developmentRight (X.developmentMk a g) t =
      X.developmentMk a (g * t) :=
  rfl

@[simp]
theorem developmentRight_one (q : X.Development) :
    X.developmentRight q 1 = q := by
  refine Quotient.inductionOn q ?_
  rintro ⟨a, g⟩
  change X.developmentMk a (g * 1) = X.developmentMk a g
  rw [mul_one]

theorem developmentRight_mul (q : X.Development) (s t : X.H) :
    X.developmentRight (X.developmentRight q s) t =
      X.developmentRight q (s * t) := by
  refine Quotient.inductionOn q ?_
  rintro ⟨a, g⟩
  change X.developmentMk a ((g * s) * t) =
    X.developmentMk a (g * (s * t))
  rw [mul_assoc]

/-- Quotient equality in the signed-word normal form. -/
theorem developmentMk_eq_iff
    {a b : V} {g h : X.H} :
    X.developmentMk a g = X.developmentMk b h ↔
      ∃ w : SignedWord ι,
        SignedWord.evalGroup X.liftGen w = g * h⁻¹ ∧
        (SignedWord.eval gen w).toPEquiv a = some b := by
  constructor
  · intro heq
    have hglue : DevelopmentGlue X (a, g) (b, h) :=
      Quotient.exact heq
    exact X.glue_iff_word.mp hglue
  · intro hw
    apply Quotient.sound
    exact X.glue_iff_word.mpr hw

/-- Canonical copy of the original vertex set, at group coordinate `1`. -/
def baseMap (a : V) : X.Development :=
  X.developmentMk a 1

/-- The canonical base copy is injective.

The proof is exactly the corrected identity-fibre argument: equality of
`[a,1]` and `[b,1]` produces an identity-fibre word mapping `a` to `b`,
and MAX forces every such word to be a partial identity. -/
theorem baseMap_injective :
    Function.Injective X.baseMap := by
  intro a b hab
  have hw := X.developmentMk_eq_iff.mp hab
  rcases hw with ⟨w, hwH, hwM⟩
  have hwH' :
      SignedWord.evalGroup X.liftGen w = (1 : X.H) := by
    simpa using hwH
  exact X.eq_of_identity_fibre_map hwH' hwM

end MaxTransporterExtension

end PSTS
end PSTSEPPA
