import PSTSEPPA.PSTS.MaxTransporter
import Mathlib.Data.Quot

/-!
# Quotient development from a maximum transporter extension

The raw points are pairs `(a,g) : V × H`.  The generating glue is

`(a, liftGen i * k) ~ (gen i (a), k)`

whenever the selected partial automorphism `gen i` is defined at `a`.

This file first proves the signed-word transport lemma.  It fixes the
orientation needed later for the equality criterion
`[a,g] = [b,h] ↔ ∃ w, evalH w = g * h⁻¹ ∧ evalM w a = b`.
-/

namespace PSTSEPPA
namespace PSTS

variable {V ι : Type*} {A : PSTS V} {gen : ι → PartialAut A}

/-- Raw points before quotienting by the generator glue. -/
abbrev DevelopmentRaw (X : MaxTransporterExtension A gen) :=
  V × X.H

/-- One positive-generator gluing step. -/
def DevelopmentGlueStep (X : MaxTransporterExtension A gen) :
    DevelopmentRaw X → DevelopmentRaw X → Prop :=
  fun x y =>
    ∃ i a b k,
      (gen i).toPEquiv a = some b ∧
      x = (a, X.liftGen i * k) ∧
      y = (b, k)

/-- Equivalence relation generated by the positive-generator glue. -/
abbrev DevelopmentGlue (X : MaxTransporterExtension A gen) :
    DevelopmentRaw X → DevelopmentRaw X → Prop :=
  Relation.EqvGen (DevelopmentGlueStep X)

namespace MaxTransporterExtension

variable (X : MaxTransporterExtension A gen)

/-- A positive letter gives one generating glue step. -/
theorem glue_pos (i : ι) {a b : V}
    (hab : (gen i).toPEquiv a = some b) (k : X.H) :
    DevelopmentGlue X
      (a, X.liftGen i * k)
      (b, k) := by
  apply Relation.EqvGen.rel
  exact ⟨i, a, b, k, hab, rfl, rfl⟩

/-- A negative letter gives the symmetric generating step. -/
theorem glue_neg (i : ι) {a b : V}
    (hab : (gen i).symm.toPEquiv a = some b) (k : X.H) :
    DevelopmentGlue X
      (a, (X.liftGen i)⁻¹ * k)
      (b, k) := by
  have hinv : (gen i).toPEquiv.symm a = some b := by
    simpa using hab
  have hba : (gen i).toPEquiv b = some a :=
    ((gen i).toPEquiv.eq_some_iff).1 hinv
  have hpos :=
    X.glue_pos i hba ((X.liftGen i)⁻¹ * k)
  have hpos' :
      DevelopmentGlue X
        (b, k)
        (a, (X.liftGen i)⁻¹ * k) := by
    simpa [mul_assoc] using hpos
  exact Relation.EqvGen.symm _ _ hpos'

/-- Any signed letter transports along the corresponding quotient glue. -/
theorem glue_letter (s : SignedLetter ι) {a b : V}
    (hab : (SignedWord.evalLetter gen s).toPEquiv a = some b)
    (k : X.H) :
    DevelopmentGlue X
      (a, SignedWord.evalGroupLetter X.liftGen s * k)
      (b, k) := by
  cases s with
  | pos i =>
      exact X.glue_pos i hab k
  | neg i =>
      exact X.glue_neg i hab k

/-- Fundamental word-glue lemma.

If the partial word maps `a` to `b`, then multiplying the group coordinate
by the group value of the same word gives equivalent raw points. -/
theorem glue_word (w : SignedWord ι) {a b : V}
    (hab : (SignedWord.eval gen w).toPEquiv a = some b)
    (k : X.H) :
    DevelopmentGlue X
      (a, SignedWord.evalGroup X.liftGen w * k)
      (b, k) := by
  induction w generalizing a b k with
  | nil =>
      have hab' : a = b := by
        simpa [SignedWord.eval] using hab
      subst b
      simpa [SignedWord.evalGroup] using
        (Relation.EqvGen.refl (DevelopmentGlueStep X) (a, k))
  | cons s w ih =>
      have hab' :
          ((SignedWord.evalLetter gen s).toPEquiv.trans
            (SignedWord.eval gen w).toPEquiv) a = some b := by
        simpa [SignedWord.eval] using hab
      rcases (PEquiv.trans_eq_some _ _ _ _).1 hab' with
        ⟨c, hac, hcb⟩
      have h₁ :=
        X.glue_letter s hac
          (SignedWord.evalGroup X.liftGen w * k)
      have h₂ := ih hcb k
      have h₁₂ := Relation.EqvGen.trans _ _ _ h₁ h₂
      simpa [SignedWord.evalGroup, mul_assoc] using h₁₂

end MaxTransporterExtension

end PSTS
end PSTSEPPA
