import PSTSEPPA.PSTS.WordEval
import Mathlib.Algebra.Group.Defs
import Mathlib.Data.Fintype.Basic

/-!
# Maximum transporter extensions

This file isolates exactly the finite-group input needed by the PSTS quotient
development.  It deliberately avoids an abstract inverse-monoid layer.

A fibre of the word evaluation in the finite group has a chosen word whose
partial action extends the partial action of every other word in that fibre.
-/

namespace PSTSEPPA
namespace PSTS
namespace SignedWord

variable {ι H : Type*}

/-- Interpret one signed generator in a group. -/
def evalGroupLetter [Group H] (liftGen : ι → H) : SignedLetter ι → H
  | .pos i => liftGen i
  | .neg i => (liftGen i)⁻¹

@[simp]
theorem evalGroupLetter_pos [Group H] (liftGen : ι → H) (i : ι) :
    evalGroupLetter liftGen (.pos i) = liftGen i :=
  rfl

@[simp]
theorem evalGroupLetter_neg [Group H] (liftGen : ι → H) (i : ι) :
    evalGroupLetter liftGen (.neg i) = (liftGen i)⁻¹ :=
  rfl

@[simp]
theorem evalGroupLetter_inv [Group H] (liftGen : ι → H) (s : SignedLetter ι) :
    evalGroupLetter liftGen s.inv = (evalGroupLetter liftGen s)⁻¹ := by
  cases s <;> simp [evalGroupLetter, SignedLetter.inv]

/-- Evaluate a signed word in a group, in the same left-to-right convention as
partial-word evaluation. -/
def evalGroup [Group H] (liftGen : ι → H) : SignedWord ι → H
  | [] => 1
  | s :: w => evalGroupLetter liftGen s * evalGroup liftGen w

@[simp]
theorem evalGroup_nil [Group H] (liftGen : ι → H) :
    evalGroup liftGen [] = 1 :=
  rfl

@[simp]
theorem evalGroup_cons [Group H] (liftGen : ι → H) (s : SignedLetter ι)
    (w : SignedWord ι) :
    evalGroup liftGen (s :: w) =
      evalGroupLetter liftGen s * evalGroup liftGen w :=
  rfl

@[simp]
theorem evalGroup_append [Group H] (liftGen : ι → H) (u v : SignedWord ι) :
    evalGroup liftGen (u ++ v) = evalGroup liftGen u * evalGroup liftGen v := by
  induction u with
  | nil =>
      simp
  | cons s u ih =>
      simp [ih, mul_assoc]

@[simp]
theorem evalGroup_inv [Group H] (liftGen : ι → H) (w : SignedWord ι) :
    evalGroup liftGen (inv w) = (evalGroup liftGen w)⁻¹ := by
  induction w with
  | nil =>
      simp
  | cons s w ih =>
      rw [inv_cons, evalGroup_append, ih]
      simp [evalGroup]

end SignedWord

variable {V ι : Type*} {A : PSTS V}

/-- A finite group extension with a maximum partial transporter in every
word-value fibre.

No generation hypothesis on `H` is needed by the quotient development:
unused elements merely produce redundant copies.  The later Cayley/ABO
construction will in fact supply a group generated by the chosen lifts. -/
structure MaxTransporterExtension (A : PSTS V) (gen : ι → PartialAut A) where
  /-- Finite ambient group receiving the selected generators. -/
  H : Type*
  /-- Group structure on the ambient finite type. -/
  [groupH : Group H]
  /-- Finiteness used to make the quotient witness finite. -/
  [fintypeH : Fintype H]
  /-- Group lift of each selected positive generator. -/
  liftGen : ι → H
  /-- Chosen maximum word in each group-value fibre. -/
  maxWord : H → SignedWord ι
  /-- The chosen word really lies in the indicated fibre. -/
  maxWord_value : ∀ h,
    SignedWord.evalGroup liftGen (maxWord h) = h
  /-- Every partial word-value in a fibre is a restriction of the chosen
  maximum partial word-value in that fibre. -/
  dominates : ∀ {h} (w : SignedWord ι),
    SignedWord.evalGroup liftGen w = h →
      (SignedWord.eval gen w).toPEquiv ≤
        (SignedWord.eval gen (maxWord h)).toPEquiv

namespace MaxTransporterExtension

variable {gen : ι → PartialAut A}

/-- A partial equivalence extending the total identity must equal the total
identity.  This is the elementary repair needed in the identity fibre. -/
theorem pEquiv_eq_refl_of_refl_le {p : V ≃. V}
    (h : PEquiv.refl V ≤ p) : p = PEquiv.refl V := by
  apply PEquiv.ext
  intro x
  have hxmem : x ∈ p x := h x x (by simp)
  have hx : p x = some x := by
    simpa only [Option.mem_def] using hxmem
  simpa using hx

/-- The selected maximum in the identity fibre has total partial value equal
to the identity.

This is deliberately *not* proved by claiming that the total identity is a
maximum of the whole restriction order.  Instead MAX gives
`refl ≤ maxWord(1)`, and totality of `refl` forces equality. -/
theorem maxWord_one_toPEquiv (X : MaxTransporterExtension A gen) :
    (SignedWord.eval gen (X.maxWord 1)).toPEquiv = PEquiv.refl V := by
  apply pEquiv_eq_refl_of_refl_le
  have hdom := X.dominates (h := (1 : X.H)) ([] : SignedWord ι) (by simp)
  simpa [SignedWord.eval] using hdom

/-- Every word in the identity group fibre acts as a partial identity. -/
theorem identity_fibre_le_refl (X : MaxTransporterExtension A gen)
    {w : SignedWord ι}
    (hw : SignedWord.evalGroup X.liftGen w = (1 : X.H)) :
    (SignedWord.eval gen w).toPEquiv ≤ PEquiv.refl V := by
  have hdom := X.dominates (h := (1 : X.H)) w hw
  rw [X.maxWord_one_toPEquiv] at hdom
  exact hdom

/-- Pointwise form of the identity-fibre repair, used for injectivity of the
base copy in the development. -/
theorem eq_of_identity_fibre_map (X : MaxTransporterExtension A gen)
    {w : SignedWord ι} {a b : V}
    (hw : SignedWord.evalGroup X.liftGen w = (1 : X.H))
    (hab : (SignedWord.eval gen w).toPEquiv a = some b) :
    a = b := by
  have hle := X.identity_fibre_le_refl hw
  have hbmem : b ∈ (SignedWord.eval gen w).toPEquiv a := by
    simpa only [Option.mem_def] using hab
  have hbmem' : b ∈ (PEquiv.refl V) a := hle a b hbmem
  have hsome : (some a : Option V) = some b := by
    simpa only [PEquiv.refl_apply, Option.mem_def] using hbmem'
  exact Option.some.inj hsome

end MaxTransporterExtension

end PSTS
end PSTSEPPA
