import PSTSEPPA.PSTS.TotalPermutationLifts
import PSTSEPPA.ABO.CayleyGraph
import Mathlib.Data.Fintype.Perm

/-!
# Finite Q generated by total lifts of selected PSTS partial automorphisms

The Cayley/MAX construction in the audited PSTS-EPPA transfer note
first chooses a total permutation extending each selected partial
automorphism, then lets Q be the FINITE group generated by those
permutations. As throughout this project, multiplication is in the
opposite permutation group to match chronological right application.

We define this subgroup concretely, prove all signed word values lie
in it, show every group element has a signed word representative and,
for a finite PSTS carrier, give the induced group a Fintype.
Finally the Cayley graph is built with exactly this selected group Q,
with positive edges Q × selected generator labels.

This is just the special C1 input, NOT a group-reflection lemma
and NOT an abstract inverse-monoid/F-inverse cover theorem.
-/

namespace PSTSEPPA
namespace PSTS

variable {V ι : Type*} {A : PSTS V}
variable {gen : ι → PartialAut A}
variable (L : TotalPermutationLifts A gen)

namespace TotalPermutationLifts

/-- The selected finite permutation group Q, represented as a
subgroup of opposite permutations on the original PSTS carrier. -/
def generatedQ : Subgroup (ABO.RightPerm V) :=
  Subgroup.closure (Set.range L.groupGenerator)

/-- Every selected total generator belongs to Q. -/
theorem groupGenerator_mem (i : ι) :
    L.groupGenerator i ∈ L.generatedQ :=
  Subgroup.subset_closure ⟨i, rfl⟩

/-- Selected generators interpreted as actual elements of Q. -/
def cayleyGenerator (i : ι) : L.generatedQ :=
  ⟨L.groupGenerator i, L.groupGenerator_mem i⟩

/-- Values of formal inverses of the selected letters are also in Q. -/
theorem signedGroupGenerator_mem (s : SignedLetter ι) :
    SignedWord.evalGroupLetter L.groupGenerator s ∈ L.generatedQ := by
  cases s with
  | pos i =>
      exact L.groupGenerator_mem i
  | neg i =>
      exact L.generatedQ.inv_mem (L.groupGenerator_mem i)

/-- Any signed-word permutation value lies in the generated group Q,
with no assumption of freeness or injective generator labels. -/
theorem groupValue_mem (w : SignedWord ι) :
    L.groupValue w ∈ L.generatedQ := by
  induction w with
  | nil =>
      exact L.generatedQ.one_mem
  | cons s w ih =>
      exact L.generatedQ.mul_mem
        (L.signedGroupGenerator_mem s) ih

/-- Each concrete selected total word has a canonical value in Q. -/
def valueQ (w : SignedWord ι) : L.generatedQ :=
  ⟨L.groupValue w, L.groupValue_mem w⟩

/-- Selected generators generate Q: every ambient permutation in Q
has a signed-word representation. This proof mirrors the actual
closure induction rather than assuming the generating alphabet
maps injectively into the permutation group. -/
theorem exists_word_groupValue_of_mem
    {g : ABO.RightPerm V} (hg : g ∈ L.generatedQ) :
    ∃ w : SignedWord ι, L.groupValue w = g := by
  change g ∈ Subgroup.closure (Set.range L.groupGenerator) at hg
  induction hg using Subgroup.closure_induction with
  | mem x hx =>
      rcases hx with ⟨i, rfl⟩
      exact ⟨[SignedLetter.pos i], by
        simp [groupValue, SignedWord.evalGroup]⟩
  | one =>
      exact ⟨[], rfl⟩
  | mul x y hx hy ihx ihy =>
      obtain ⟨u, hu⟩ := ihx
      obtain ⟨v, hv⟩ := ihy
      refine ⟨u ++ v, ?_⟩
      calc
        L.groupValue (u ++ v) =
          L.groupValue u * L.groupValue v :=
            SignedWord.evalGroup_append L.groupGenerator u v
        _ = x * y := by rw [hu, hv]
  | inv x hx ih =>
      obtain ⟨u, hu⟩ := ih
      refine ⟨SignedWord.inv u, ?_⟩
      calc
        L.groupValue (SignedWord.inv u) =
          (L.groupValue u)⁻¹ :=
            SignedWord.evalGroup_inv L.groupGenerator u
        _ = x⁻¹ := congrArg Inv.inv hu

/-- Every element of the actual selected subgroup Q has a word
representative in the original signed generator alphabet. -/
theorem exists_word_valueQ (q : L.generatedQ) :
    ∃ w : SignedWord ι, L.valueQ w = q := by
  obtain ⟨w, hw⟩ := L.exists_word_groupValue_of_mem q.property
  refine ⟨w, ?_⟩
  apply Subtype.ext
  exact hw

/-- On a finite PSTS carrier, Q is finite as a subgroup of the
finite group of total permutations. DecidableEq on the carrier
is installed classically; no algorithmic enumeration is required. -/
noncomputable instance [Fintype V] : Fintype L.generatedQ := by
  classical
  letI : Fintype (Equiv.Perm V) := inferInstance
  letI : Fintype (ABO.RightPerm V) := inferInstance
  exact Fintype.ofFinite _

/-- The actual complete oriented Cayley EGraph used by the
specialized ABO-to-fibre-MAX argument. Its positive edge alphabet
is Q × ι; inverse edges are separate formal signed tokens. -/
noncomputable def selectedCayley :=
  ABO.cayleyGraph L.cayleyGenerator

end TotalPermutationLifts
end PSTS
end PSTSEPPA
