import PSTSEPPA.PSTS.SelectedFinitePermutationGroup

/-!
# Word endpoints in the actual finite selected Cayley group Q

With the total-permutation lifts of the selected PSTS partial
automorphisms, define Q as the subgroup generated by their
opposite-permutation values. The specialized Cayley graph must
interpret words with the SAME group value as their total actions.

This file checks that the original chronological word evaluation
agrees under coercion with the signed-word value computed directly
in Q. The endpoint of the true Cayley path from q is therefore
q times this very Q-value, and the path from the identity ends
at that value.

No extension to general ABO graph automorphisms, no content
hypothesis and no group-reflection theorem are used.
-/

namespace PSTSEPPA
namespace PSTS

variable {V ι : Type*} {A : PSTS V} {gen : ι → PartialAut A}
variable (L : TotalPermutationLifts A gen)

namespace TotalPermutationLifts

/-- Evaluating selected signed words in Q and then forgetting the
subgroup type agrees exactly with their evaluation in opposite
permutations of the PSTS carrier. Chronological orientation matters. -/
theorem selectedCayley_wordValue_coe (w : SignedWord ι) :
    ((SignedWord.evalGroup L.cayleyGenerator w :
      L.generatedQ) : ABO.RightPerm V) = L.groupValue w := by
  induction w with
  | nil =>
      rfl
  | cons s w ih =>
      cases s with
      | pos i =>
          change
            L.groupGenerator i *
              ((SignedWord.evalGroup L.cayleyGenerator w :
                L.generatedQ) : ABO.RightPerm V) =
            L.groupGenerator i * L.groupValue w
          rw [ih]
      | neg i =>
          change
            (L.groupGenerator i)⁻¹ *
              ((SignedWord.evalGroup L.cayleyGenerator w :
                L.generatedQ) : ABO.RightPerm V) =
            (L.groupGenerator i)⁻¹ * L.groupValue w
          rw [ih]

/-- The signed word's direct Q-value is precisely the same
subgroup element as the total-permutation word value. -/
theorem selectedCayley_wordValue_eq_valueQ (w : SignedWord ι) :
    (SignedWord.evalGroup L.cayleyGenerator w : L.generatedQ) =
      L.valueQ w := by
  apply Subtype.ext
  exact L.selectedCayley_wordValue_coe w

/-- Endpoint of a true signed Cayley path from q, with all letters
in chronological order, is q multiplied by the partial-generator
word's selected total permutation value in Q. -/
theorem selectedCayley_followWord (q : L.generatedQ)
    (w : SignedWord ι) :
    (L.selectedCayley).followWord q w = q * L.valueQ w := by
  change (ABO.cayleyGraph L.cayleyGenerator).followWord q w =
    q * L.valueQ w
  rw [ABO.cayleyGraph.followWord_eq_mul_evalGroup,
    L.selectedCayley_wordValue_eq_valueQ]

/-- The Cayley path starting at the identity ends at the EXACT
selected total permutation group value of the signed word. -/
theorem selectedCayley_identity_endpoint (w : SignedWord ι) :
    (L.selectedCayley).followWord 1 w = L.valueQ w := by
  rw [L.selectedCayley_followWord]
  exact one_mul _

/-- Equality of Q-valued Cayley word endpoints from the identity
is equivalent to equality of total signed permutation word values. -/
theorem valueQ_eq_iff_groupValue_eq
    (u v : SignedWord ι) :
    L.valueQ u = L.valueQ v ↔
      L.groupValue u = L.groupValue v := by
  constructor
  · intro h
    exact congrArg Subtype.val h
  · intro h
    exact Subtype.ext h

end TotalPermutationLifts
end PSTS
end PSTSEPPA
