import PSTSEPPA.ABO.CayleySubgraph

/-!
# ABO Definition 3.16: admissibility for coset extensions

Here the skeleton is an arbitrary A-labelled Cayley subgraph, not necessarily
complete.  All connectivity below is *intrinsic*: a C-component consists of
vertices connected by an actual C-labelled path in the skeleton.

ABO admissibility says that, inside one intrinsic B-component of the
skeleton, two disjoint intrinsic subcomponents on proper alphabets B₁,B₂ ⊂ B
cannot have intersecting ambient group cosets.  We give the contrapositive
form: ambient coset overlap must be reflected by a common skeleton vertex
reachable using B₁ and B₂ respectively.

The source uses B₁,B₂ ⊂ B ⊂ A, with all containments strict.  Equal
alphabets B₁ = B₂ are allowed, as are empty B₁ or B₂; the latter degenerate
cases are especially important for the rank-two base case.
-/

namespace PSTSEPPA
namespace ABO

variable {ι Γ : Type*}
variable [Fintype ι] [DecidableEq ι] [Group Γ]

/-- The subgroup generated by the empty alphabet is trivial. -/
theorem generatedSubgroup_empty (gen : ι → Γ) :
    generatedSubgroup gen (∅ : Finset ι) = ⊥ := by
  apply le_antisymm
  · unfold generatedSubgroup
    apply (Subgroup.closure_le _).2
    rintro x ⟨i, rfl⟩
    have hi : False := by simpa using i.2
    exact hi.elim
  · exact bot_le

/-- The coset for the empty alphabet is a singleton, including for trivial
ambient groups or repeated/trivial labelled generators. -/
theorem generatedLeftCoset_empty_eq_singleton
    (gen : ι → Γ) (v : Γ) :
    generatedLeftCoset gen (∅ : Finset ι) v = {v} := by
  ext x
  change
    (v⁻¹ * x ∈ generatedSubgroup gen ∅) ↔ x = v
  rw [generatedSubgroup_empty]
  change (v⁻¹ * x = 1) ↔ x = v
  constructor
  · intro hx
    have hm := congrArg (fun t : Γ => v * t) hx
    simpa [mul_assoc] using hm
  · intro hx
    rw [hx]
    simp

namespace CayleySubgraphSpec

variable {gen : ι → Γ} {A : Finset ι}

/-- ABO Definition 3.16, in equivalent overlap-reflection form.

Given B ⊂ A and B₁,B₂ ⊂ B, take two vertices x,y connected by a B-path
inside K. If the ambient left cosets xG[B₁] and yG[B₂] meet, then there
must be a vertex z of K reachable from x by a B₁-path and from y by a
B₂-path. Equivalently, disjoint intrinsic subcomponents cannot acquire an
unintended intersection in the ambient group.

The source imposes connectedness of K and retractability of G[A] as
environmental prerequisites of the extension construction; these are not
built into this local predicate. -/
def AdmissibleForCosetExtension
    (K : CayleySubgraphSpec gen A) : Prop :=
  ∀ (B B₁ B₂ : Finset ι),
    B ⊂ A → B₁ ⊂ B → B₂ ⊂ B →
    ∀ (x y : K.Vertex),
      K.SubalphabetReachable B x y →
      (generatedLeftCoset gen B₁ x.1 ∩
        generatedLeftCoset gen B₂ y.1).Nonempty →
      ∃ z : K.Vertex,
        K.SubalphabetReachable B₁ x z ∧
        K.SubalphabetReachable B₂ y z

/-- An immediate consequence of the definition: if both intrinsic
subcomponents avoid each other, so do their ambient cosets. This is the
disjointness formulation (3.5) of ABO Definition 3.16. -/
theorem admissible_implies_ambient_disjoint
    (K : CayleySubgraphSpec gen A)
    (hadm : K.AdmissibleForCosetExtension)
    (B B₁ B₂ : Finset ι)
    (hB : B ⊂ A) (hB₁ : B₁ ⊂ B) (hB₂ : B₂ ⊂ B)
    (x y : K.Vertex)
    (hxy : K.SubalphabetReachable B x y)
    (hdisj :
      ¬ ∃ z : K.Vertex,
        K.SubalphabetReachable B₁ x z ∧
        K.SubalphabetReachable B₂ y z) :
    generatedLeftCoset gen B₁ x.1 ∩
      generatedLeftCoset gen B₂ y.1 = ∅ := by
  ext g
  constructor
  · intro hg
    have hn :
        (generatedLeftCoset gen B₁ x.1 ∩
          generatedLeftCoset gen B₂ y.1).Nonempty :=
      ⟨g, hg⟩
    exact (hdisj (hadm B B₁ B₂ hB hB₁ hB₂ x y hxy hn)).elim
  · intro hg
    exact (Set.not_mem_empty g hg).elim

/-- The low-rank admissibility repair needed at the base of the ABO
induction (Proposition 4.4 / repair R4).

For |A| ≤ 2, every B ⊂ A has |B| ≤ 1, so both B₁,B₂ ⊂ B must be empty.
Consequently the ambient cosets in Definition 3.16 are singletons; whenever
they meet, x=y, and the singleton vertex is a common intrinsic point.
This needs no retractability or connectedness hypotheses. -/
theorem admissible_of_card_le_two
    (K : CayleySubgraphSpec gen A) (hA : A.card ≤ 2) :
    K.AdmissibleForCosetExtension := by
  intro B B₁ B₂ hB hB₁ hB₂ x y _hxy hamb
  have hBcard : B.card < A.card := Finset.card_lt_card hB
  have hB₁card : B₁.card < B.card := Finset.card_lt_card hB₁
  have hB₂card : B₂.card < B.card := Finset.card_lt_card hB₂
  have hBle1 : B.card ≤ 1 :=
    Nat.lt_succ_iff.mp (lt_of_lt_of_le hBcard hA)
  have hB₁zero : B₁.card = 0 :=
    Nat.eq_zero_of_le_zero
      (Nat.lt_succ_iff.mp (lt_of_lt_of_le hB₁card hBle1))
  have hB₂zero : B₂.card = 0 :=
    Nat.eq_zero_of_le_zero
      (Nat.lt_succ_iff.mp (lt_of_lt_of_le hB₂card hBle1))
  have hB₁empty : B₁ = ∅ :=
    Finset.card_eq_zero.mp hB₁zero
  have hB₂empty : B₂ = ∅ :=
    Finset.card_eq_zero.mp hB₂zero
  rcases hamb with ⟨z, hz₁, hz₂⟩
  have hxz : z = x.1 := by
    simpa [hB₁empty, generatedLeftCoset_empty_eq_singleton] using hz₁
  have hyz : z = y.1 := by
    simpa [hB₂empty, generatedLeftCoset_empty_eq_singleton] using hz₂
  have hxy : x = y := Subtype.ext (hxz.symm.trans hyz)
  refine ⟨x, K.subalphabetReachable_refl B₁ x, ?_⟩
  rw [← hxy]
  exact K.subalphabetReachable_refl B₂ x

end CayleySubgraphSpec

end ABO
end PSTSEPPA
