import PSTSEPPA.ABO.CayleyPositivePathSupport
import Mathlib.GroupTheory.SemidirectProduct

/-!
# The exact Cayley semidirect-word formula for PSTS fibre-MAX

The audited PSTS transfer uses H generated by lifts
  h_i = (edgeG(1,i), genQ i) ∈ G ⋊ Q,
where Q acts by LEFT translations on the positive Cayley
edge-labelled finite group G.

This module proves the exact group-word formula before any
hard content-reflection theorem is invoked:

  evalH(w) = (pathG(1,w), evalQ(w)).

Here pathG(q,w) is the value of the TRUE oriented Cayley path,
using edgeG(q,i) for a forward signed step and the inverse of
edgeG(q*genQ(i)^-1,i) for a backwards step.

The only action hypothesis is equivariance on E = Q × ι:
  φ(t)(edgeG(q,i)) = edgeG(t*q,i).
No equivariance under the full automorphism group of arbitrary
oriented graphs is needed.

This is a direct specialisation of equation (Hvalue) in the
project's audited source. It does NOT assert existence of a
finite G with the hard content/retractability/path-reduction
property. It ensures the ensuing content certificate's H→Q
projection is the right one with correct signed orientations.
-/

namespace PSTSEPPA
namespace ABO

variable {G Q ι : Type*} [Group G] [Group Q]

/-- The G-value of the genuine signed Cayley path from q.
The positive edge alphabet is E=Q×ι; a negative step in
direction i uses the inverse of the edge based at q*gen(i)^-1. -/
def cayleyPathGroupValue (gen : ι → Q) (edge : Q × ι → G)
    (q : Q) : LabelWord ι → G
  | [] => 1
  | PSTS.SignedLetter.pos i :: w =>
      edge (q, i) * cayleyPathGroupValue gen edge (q * gen i) w
  | PSTS.SignedLetter.neg i :: w =>
      (edge (q * (gen i)⁻¹, i))⁻¹ *
        cayleyPathGroupValue gen edge (q * (gen i)⁻¹) w

@[simp]
theorem cayleyPathGroupValue_nil
    (gen : ι → Q) (edge : Q × ι → G) (q : Q) :
    cayleyPathGroupValue gen edge q ([] : LabelWord ι) = 1 := rfl

/-- Equivariance of every SIGNED Cayley path under left Q-translation,
assuming only equivariance of the generators indexed by E=Q×ι. -/
theorem cayleyPathGroupValue_left
    (φ : Q →* MulAut G) (gen : ι → Q) (edge : Q × ι → G)
    (hEdge : ∀ (t q : Q) (i : ι),
      φ t (edge (q,i)) = edge (t*q,i))
    (t q : Q) (w : LabelWord ι) :
    φ t (cayleyPathGroupValue gen edge q w) =
      cayleyPathGroupValue gen edge (t*q) w := by
  induction w generalizing q with
  | nil =>
      simp [cayleyPathGroupValue]
  | cons s w ih =>
      cases s with
      | pos i =>
          change φ t
              (edge (q,i) * cayleyPathGroupValue gen edge (q * gen i) w) =
            edge (t*q,i) *
              cayleyPathGroupValue gen edge ((t*q) * gen i) w
          rw [map_mul, hEdge t q i, ih (q := q * gen i)]
          simp [mul_assoc]
      | neg i =>
          change φ t
              ((edge (q * (gen i)⁻¹,i))⁻¹ *
                cayleyPathGroupValue gen edge (q * (gen i)⁻¹) w) =
            (edge ((t*q) * (gen i)⁻¹,i))⁻¹ *
              cayleyPathGroupValue gen edge ((t*q) * (gen i)⁻¹) w
          rw [map_mul, map_inv, hEdge t (q * (gen i)⁻¹) i,
            ih (q := q * (gen i)⁻¹)]
          simp [mul_assoc]

/-- Signed generator h_i of the future reflecting subgroup
H≤G⋊Q: its first coordinate is the G-value of the positive
Cayley edge (1,i), and its second is the total group Q-generator. -/
def cayleySemidirectGenerator
    (φ : Q →* MulAut G) (gen : ι → Q)
    (edge : Q × ι → G) (i : ι) :
    G ⋊[φ] Q :=
  ⟨edge (1,i), gen i⟩

/-- The backwards lift h_i^-1 has the correct Cayley positive
edge at gen(i)^-1 (not at identity). This is the critical
oriented-edge calculation in the semidirect formula. -/
theorem cayleySemidirectGenerator_inv_left
    (φ : Q →* MulAut G) (gen : ι → Q)
    (edge : Q × ι → G)
    (hEdge : ∀ (t q : Q) (i : ι),
      φ t (edge (q,i)) = edge (t*q,i))
    (i : ι) :
    ((cayleySemidirectGenerator φ gen edge i)⁻¹).left =
      (edge ((gen i)⁻¹,i))⁻¹ := by
  change φ ((gen i)⁻¹) ((edge (1,i))⁻¹) =
    (edge ((gen i)⁻¹,i))⁻¹
  rw [map_inv]
  exact congrArg Inv.inv (by simpa using hEdge ((gen i)⁻¹) 1 i)

/-- Exact signed-word value equality in the semidirect product:
the first component is the actual path's G-value, and the second
component is the total selected Cayley Q-value.

This holds for inverse signed letters, degenerate Q-generators,
and geometric loops, given only the Q-action equivariance hEdge. -/
theorem cayleySemidirect_wordValue
    (φ : Q →* MulAut G) (gen : ι → Q)
    (edge : Q × ι → G)
    (hEdge : ∀ (t q : Q) (i : ι),
      φ t (edge (q,i)) = edge (t*q,i))
    (w : LabelWord ι) :
    PSTS.SignedWord.evalGroup
        (cayleySemidirectGenerator φ gen edge) w =
      (⟨cayleyPathGroupValue gen edge 1 w,
        PSTS.SignedWord.evalGroup gen w⟩ : G ⋊[φ] Q) := by
  induction w with
  | nil =>
      rfl
  | cons s w ih =>
      cases s with
      | pos i =>
          rw [PSTS.SignedWord.evalGroup_cons, ih]
          apply SemidirectProduct.ext
          · change
              edge (1,i) *
                φ (gen i) (cayleyPathGroupValue gen edge 1 w) =
              edge (1,i) * cayleyPathGroupValue gen edge (1 * gen i) w
            rw [cayleyPathGroupValue_left φ gen edge hEdge (gen i) 1 w]
            simp
          · change gen i * PSTS.SignedWord.evalGroup gen w =
              PSTS.SignedWord.evalGroup gen
                (PSTS.SignedLetter.pos i :: w)
            rfl
      | neg i =>
          rw [PSTS.SignedWord.evalGroup_cons, ih]
          apply SemidirectProduct.ext
          · change
              ((cayleySemidirectGenerator φ gen edge i)⁻¹).left *
                φ (((cayleySemidirectGenerator φ gen edge i)⁻¹).right)
                  (cayleyPathGroupValue gen edge 1 w) =
              (edge (1 * (gen i)⁻¹,i))⁻¹ *
                cayleyPathGroupValue gen edge (1 * (gen i)⁻¹) w
            rw [cayleySemidirectGenerator_inv_left φ gen edge hEdge i]
            change
              (edge ((gen i)⁻¹,i))⁻¹ *
                φ ((gen i)⁻¹) (cayleyPathGroupValue gen edge 1 w) =
              (edge (1 * (gen i)⁻¹,i))⁻¹ *
                cayleyPathGroupValue gen edge (1 * (gen i)⁻¹) w
            rw [cayleyPathGroupValue_left φ gen edge hEdge ((gen i)⁻¹) 1 w]
            simp
          · change (gen i)⁻¹ * PSTS.SignedWord.evalGroup gen w =
              PSTS.SignedWord.evalGroup gen
                (PSTS.SignedLetter.neg i :: w)
            rfl

end ABO
end PSTSEPPA
