import PSTSEPPA.ABO.Retractability
import Mathlib.GroupTheory.SemidirectProduct
import Mathlib.Algebra.Group.Action.End

/-!
# Coherent Cayley-left translation action from individual symmetries

Corrected ABO I Proposition 5.5 constructs automorphisms of the
final reflecting group G extending automorphisms of the input
oriented labelled graph. For the PSTS Cayley specialization,
the relevant graph automorphisms are LEFT translations by Q.

It is enough to produce an extension automorphism β_t of G for
each t in Q, satisfying
  β_t(edge(q,i)) = edge(t*q,i).

If the full positive edge family E=Q×ι generates G, two group
automorphisms agreeing on E are equal everywhere. Therefore the
individual extensions are AUTOMATICALLY coherent:
  β_1 = id,   β_(t*s) = β_t ∘ β_s.

This module certifies uniqueness and packages the assignment
as an actual group homomorphism Q →* MulAut G, precisely the
left Q-equivariant action demanded by the semidirect H≤G⋊Q
and the already-certified PSTS fibre-MAX transfer.

It does NOT assert the existence of the individual β_t,
or the construction of the reflecting group G. These remain
the Section 5 finite-construction/Proposition-5.5 obligations.
-/

namespace PSTSEPPA
namespace ABO

variable {E G Q ι : Type*} [Group G] [Group Q]

/-- A group automorphism of a group generated by labelled elements
is uniquely determined by its images on those generators.

No injectivity of the generator map is required; repeated,
trivial and loop edge labels are allowed. -/
theorem mulAut_eq_of_generator_images
    (edge : E → G) (hgen : IsGenerated edge)
    (α β : MulAut G)
    (hEq : ∀ e : E, α (edge e) = β (edge e)) :
    α = β := by
  apply MulEquiv.ext
  intro g
  have hg : g ∈ Subgroup.closure (Set.range edge) := by
    rw [hgen]
    trivial
  induction hg using Subgroup.closure_induction with
  | mem x hx =>
      obtain ⟨e, rfl⟩ := hx
      exact hEq e
  | one =>
      simp
  | mul x y hx hy ihx ihy =>
      simp [ihx, ihy]
  | inv x hx ih =>
      simp [ih]

/-- If automorphisms of G have been constructed for EACH individual
left translation of the Cayley edge alphabet Q×ι, generatedness
forces their group law and identity law. Hence they extend
uniquely to one coherent homomorphism Q→*MulAut(G).

This supplies the exact semidirect-product input without
postulating coherence as an independent mathematical theorem. -/
def coherentCayleyLeftAction
    (edge : Q × ι → G) (hgen : IsGenerated edge)
    (β : Q → MulAut G)
    (hβ : ∀ (t q : Q) (i : ι),
      β t (edge (q, i)) = edge (t * q, i)) :
    Q →* MulAut G where
  toFun := β
  map_one' := by
    apply mulAut_eq_of_generator_images edge hgen
    rintro ⟨q, i⟩
    simpa using hβ 1 q i
  map_mul' t s := by
    apply mulAut_eq_of_generator_images edge hgen
    rintro ⟨q, i⟩
    calc
      β (t * s) (edge (q, i)) =
          edge ((t * s) * q, i) := hβ (t * s) q i
      _ = edge (t * (s * q), i) := by rw [mul_assoc]
      _ = β t (edge (s * q, i)) := (hβ t (s * q) i).symm
      _ = β t (β s (edge (q, i))) := by rw [hβ s q i]
      _ = (β t * β s) (edge (q, i)) := by
        rw [MulAut.mul_apply]

/-- The resulting action still has precisely the required
positive-edge left-Q equivariance law. -/
theorem coherentCayleyLeftAction_edge
    (edge : Q × ι → G) (hgen : IsGenerated edge)
    (β : Q → MulAut G)
    (hβ : ∀ (t q : Q) (i : ι),
      β t (edge (q, i)) = edge (t * q, i))
    (t q : Q) (i : ι) :
    (coherentCayleyLeftAction edge hgen β hβ) t (edge (q, i)) =
      edge (t * q, i) :=
  hβ t q i

/-- Two coherent extensions of the left Q-action are equal if
they agree with left translations on the generating edge labels. -/
theorem coherentCayleyLeftAction_unique
    (edge : Q × ι → G) (hgen : IsGenerated edge)
    (Φ Ψ : Q →* MulAut G)
    (hΦ : ∀ (t q : Q) (i : ι),
      Φ t (edge (q,i)) = edge (t * q,i))
    (hΨ : ∀ (t q : Q) (i : ι),
      Ψ t (edge (q,i)) = edge (t * q,i)) :
    Φ = Ψ := by
  apply MonoidHom.ext
  intro t
  apply mulAut_eq_of_generator_images edge hgen
  rintro ⟨q,i⟩
  exact (hΦ t q i).trans (hΨ t q i).symm

end ABO
end PSTSEPPA
