import PSTSEPPA.ABO.ClusterComponentGraph
import PSTSEPPA.ABO.Stability
/-!
# Stability transport for ABO clusters

This file formalizes the labelled-graph content of ABO Lemma 3.10.

A labelled quotient sends the cluster determined by a fixed family of proper
subalphabets to the corresponding cluster downstairs.  If the quotient is
stable on every constituent alphabet, and the target group is retractable,
this cluster map is bijective on both vertices and directed edge tokens.

The source-facing k-stable corollary uses only the properness of the
constituent alphabets: every constituent of an A-cluster has cardinality at
most k-1 when |A| = k.
-/

namespace PSTSEPPA
namespace ABO

variable {ι Γ Δ : Type*}
variable [Fintype ι] [DecidableEq ι] [Group Γ] [Group Δ]
variable {genΓ : ι → Γ} {genΔ : ι → Δ}

namespace LabelledGroupQuotient

variable (Q : LabelledGroupQuotient genΓ genΔ)

/-- The labelled quotient induces the evident labelled graph morphism between
corresponding clusters. -/
noncomputable def clusterHom
    {A : Finset ι} (P : ClusterSpec A) :
    LabelledGraphHom
      (P.toLabelledGraph genΓ)
      (P.toLabelledGraph genΔ) where
  onVertex x :=
    ⟨Q.hom x.1, by
      rcases x.2 with ⟨B, hBP, hxB⟩
      exact
        ⟨B, hBP,
          Q.hom_mem_generatedSubgroup B hxB⟩⟩
  onEdge e :=
    ⟨(Q.hom e.1.1, e.1.2), by
      rcases e.2 with ⟨B, hBP, hs, hl⟩
      exact
        ⟨B, hBP,
          Q.hom_mem_generatedSubgroup B hs,
          hl⟩⟩
  map_source e := by
    apply Subtype.ext
    rfl
  map_inv e := by
    apply Subtype.ext
    rcases e with ⟨⟨x, s⟩, he⟩
    cases s with
    | pos i =>
        change
          (Q.hom (x * genΓ i), PSTS.SignedLetter.neg i) =
            (Q.hom x * genΔ i, PSTS.SignedLetter.neg i)
        rw [map_mul, Q.map_gen]
    | neg i =>
        change
          (Q.hom (x * (genΓ i)⁻¹), PSTS.SignedLetter.pos i) =
            (Q.hom x * (genΔ i)⁻¹, PSTS.SignedLetter.pos i)
        rw [map_mul, map_inv, Q.map_gen]
  map_label e := rfl

@[simp]
theorem clusterHom_onVertex_val
    {A : Finset ι} (P : ClusterSpec A)
    (x : P.Vertex genΓ) :
    ((Q.clusterHom P).onVertex x).1 = Q.hom x.1 :=
  rfl

@[simp]
theorem clusterHom_onEdge_val
    {A : Finset ι} (P : ClusterSpec A)
    (e : P.Edge genΓ) :
    ((Q.clusterHom P).onEdge e).1 =
      (Q.hom e.1.1, e.1.2) :=
  rfl

/-- Stability on the constituent alphabets makes the ambient quotient
injective on the whole cluster vertex set.  The only nontrivial point is when
the two vertices initially lie in different constituents.  Retractability
downstairs moves their common image into the subgroup generated by the
intersection alphabet, where it has a common preimage upstairs. -/
theorem hom_injective_on_clusterVertexSet
    {A : Finset ι} (P : ClusterSpec A)
    (hgenΔ : IsGenerated genΔ) (hretΔ : Retractable genΔ)
    (hstable :
      ∀ B ∈ P.pieces, Q.StableAt B)
    {x y : Γ}
    (hx : x ∈ P.VertexSet genΓ)
    (hy : y ∈ P.VertexSet genΓ)
    (hxy : Q.hom x = Q.hom y) :
    x = y := by
  rcases hx with ⟨B, hBP, hxB⟩
  rcases hy with ⟨C, hCP, hyC⟩
  have hQxB :
      Q.hom x ∈ generatedSubgroup genΔ B :=
    Q.hom_mem_generatedSubgroup B hxB
  have hQxC :
      Q.hom x ∈ generatedSubgroup genΔ C := by
    rw [hxy]
    exact Q.hom_mem_generatedSubgroup C hyC
  have hQxInter :
      Q.hom x ∈ generatedSubgroup genΔ (B ∩ C) := by
    rw [← generatedSubgroup_inf genΔ hgenΔ hretΔ B C]
    exact ⟨hQxB, hQxC⟩
  rcases Q.exists_subgroup_preimage (B ∩ C) hQxInter with
    ⟨z, hzInter, hzmap⟩
  have hzB :
      z ∈ generatedSubgroup genΓ B :=
    generatedSubgroup_mono genΓ
      (by
        intro i hi
        exact (Finset.mem_inter.mp hi).1)
      hzInter
  have hzC :
      z ∈ generatedSubgroup genΓ C :=
    generatedSubgroup_mono genΓ
      (by
        intro i hi
        exact (Finset.mem_inter.mp hi).2)
      hzInter
  have hxz : x = z := by
    have heq :
        Q.subgroupHom B ⟨x, hxB⟩ =
          Q.subgroupHom B ⟨z, hzB⟩ := by
      apply Subtype.ext
      exact hzmap.symm
    exact congrArg Subtype.val ((hstable B hBP) heq)
  have hyz : y = z := by
    have heq :
        Q.subgroupHom C ⟨y, hyC⟩ =
          Q.subgroupHom C ⟨z, hzC⟩ := by
      apply Subtype.ext
      exact hxy.symm.trans hzmap.symm
    exact congrArg Subtype.val ((hstable C hCP) heq)
  exact hxz.trans hyz.symm

/-- Under stability on all constituent alphabets, the induced cluster map is
bijective on vertices. -/
theorem clusterHom_vertex_bijective
    {A : Finset ι} (P : ClusterSpec A)
    (hgenΔ : IsGenerated genΔ) (hretΔ : Retractable genΔ)
    (hstable :
      ∀ B ∈ P.pieces, Q.StableAt B) :
    Function.Bijective (Q.clusterHom P).onVertex := by
  constructor
  · intro x y hxy
    apply Subtype.ext
    exact
      Q.hom_injective_on_clusterVertexSet
        P hgenΔ hretΔ hstable
        x.2 y.2
        (congrArg Subtype.val hxy)
  · intro y
    rcases y with ⟨y, hy⟩
    rcases hy with ⟨B, hBP, hyB⟩
    rcases Q.exists_subgroup_preimage B hyB with
      ⟨x, hxB, hxy⟩
    refine
      ⟨⟨x, ⟨B, hBP, hxB⟩⟩, ?_⟩
    apply Subtype.ext
    exact hxy

/-- Under stability on all constituent alphabets, the induced cluster map is
bijective on directed edge tokens as well. -/
theorem clusterHom_edge_bijective
    {A : Finset ι} (P : ClusterSpec A)
    (hgenΔ : IsGenerated genΔ) (hretΔ : Retractable genΔ)
    (hstable :
      ∀ B ∈ P.pieces, Q.StableAt B) :
    Function.Bijective (Q.clusterHom P).onEdge := by
  constructor
  · intro e f hef
    apply Subtype.ext
    have hpair :
        (Q.hom e.1.1, e.1.2) =
          (Q.hom f.1.1, f.1.2) := by
      exact congrArg Subtype.val hef
    apply Prod.ext
    · exact
        Q.hom_injective_on_clusterVertexSet
          P hgenΔ hretΔ hstable
          (P.edge_source_mem genΓ e.2)
          (P.edge_source_mem genΓ f.2)
          (congrArg Prod.fst hpair)
    · exact congrArg Prod.snd hpair
  · intro e
    rcases e with ⟨⟨y, s⟩, he⟩
    rcases he with ⟨B, hBP, hyB, hsB⟩
    rcases Q.exists_subgroup_preimage B hyB with
      ⟨x, hxB, hxy⟩
    refine
      ⟨⟨(x, s), ⟨B, hBP, hxB, hsB⟩⟩, ?_⟩
    apply Subtype.ext
    apply Prod.ext
    · exact hxy
    · rfl

/-- Piecewise stability gives a labelled-graph isomorphism in the concrete
sense needed downstream: the canonical labelled graph morphism is bijective
on vertices and on directed edges. -/
theorem clusterHom_bijective_of_stablePieces
    {A : Finset ι} (P : ClusterSpec A)
    (hgenΔ : IsGenerated genΔ) (hretΔ : Retractable genΔ)
    (hstable :
      ∀ B ∈ P.pieces, Q.StableAt B) :
    Function.Bijective (Q.clusterHom P).onVertex ∧
      Function.Bijective (Q.clusterHom P).onEdge :=
  ⟨Q.clusterHom_vertex_bijective P hgenΔ hretΔ hstable,
    Q.clusterHom_edge_bijective P hgenΔ hretΔ hstable⟩

/-- Source-facing form of ABO Lemma 3.10.

If |A| = k and the labelled quotient is (k-1)-stable, then corresponding
A-clusters are isomorphic.  Properness of every constituent alphabet turns
(k-1)-stability into the piecewise stability required above. -/
theorem clusterHom_bijective_of_kStable
    {A : Finset ι} (P : ClusterSpec A)
    (hgenΔ : IsGenerated genΔ) (hretΔ : Retractable genΔ)
    {k : Nat} (hcard : A.card = k)
    (hk : Q.KStable (k - 1)) :
    Function.Bijective (Q.clusterHom P).onVertex ∧
      Function.Bijective (Q.clusterHom P).onEdge := by
  apply
    Q.clusterHom_bijective_of_stablePieces
      P hgenΔ hretΔ
  intro B hBP
  apply hk B
  have hlt : B.card < A.card :=
    Finset.card_lt_card (P.proper B hBP)
  rw [hcard] at hlt
  exact Nat.le_sub_one_of_lt hlt

end LabelledGroupQuotient

end ABO
end PSTSEPPA
