import PSTSEPPA.ABO.StabilityRetractability
import PSTSEPPA.ABO.RetractabilityRetraction

/-!
# A k-retractable labelled group gives retractable subalphabet completions

The corrected ABO induction does NOT supply global retractability of its
intermediate H₁: what is available is rank-TWO retractability. Much of the
existing literal Cayley skeleton/coset-extension geometry was formalized
under stronger global Retractable hypotheses.

The key local-algebraic transfer is therefore crucial:

Given a labelled group Γ whose relations are stable under deletion of
one generator whenever the word support has ≤k elements, let A be
ANY subalphabet with |A|≤k. Consider the GROUP generated by A,
with all labels outside A acting trivially, i.e. the genuine
trivialCompletionGenerator gen A.

THIS smaller labelled group is GLOBALLY RETRACTABLE. Even an arbitrary
word in the full label alphabet has the same evaluated value as its
restriction to A; these restricted words USE A and hence are covered
by the original k-retractability hypothesis. Deleting one generator
commutes with restriction, so equality remains true after deletion
inside the completed subgroup.

We prove the exact signed-word filtering and restriction calculus
(including inverse signs), and then the global retractability
claim without any generation, finiteness, or freeness hypothesis
on the ambient Γ. The actual subgroup inherits an obvious
generating alphabet by construction; constructing that group as
a Section-5 H₁-local replacement is separate.
-/

namespace PSTSEPPA
namespace ABO

namespace LabelWord

variable {ι : Type*} [Fintype ι] [DecidableEq ι]

/-- Signed-word erasures of two generator sets commute,
even when the deleted sets intersect, and for inverse letters. -/
theorem deleteGenerators_commute
    (D E : Finset ι) (w : LabelWord ι) :
    deleteGenerators D (deleteGenerators E w) =
      deleteGenerators E (deleteGenerators D w) := by
  induction w with
  | nil => rfl
  | cons s w ih =>
      by_cases hD : signedBase s ∈ D
      · by_cases hE : signedBase s ∈ E
        · simpa [deleteGenerators, hD, hE] using ih
        · simpa [deleteGenerators, hD, hE] using ih
      · by_cases hE : signedBase s ∈ E
        · simpa [deleteGenerators, hD, hE] using ih
        · simpa [deleteGenerators, hD, hE, ih]

/-- Restriction of a word to A commutes with erasure
of any single generator, inside or outside A. -/
theorem restrictTo_eraseGenerator
    (A : Finset ι) (a : ι) (w : LabelWord ι) :
    restrictTo A (eraseGenerator a w) =
      eraseGenerator a (restrictTo A w) := by
  exact deleteGenerators_commute (Finset.univ \ A) {a} w

/-- The actual restricted signed word is supported
entirely inside A, including when A is empty. -/
theorem uses_restrictTo (A : Finset ι) (w : LabelWord ι) :
    Uses A (restrictTo A w) := by
  induction w with
  | nil => trivial
  | cons s w ih =>
      by_cases hs : signedBase s ∈ A
      · have hs' : signedBase s ∉ Finset.univ \ A := by
          simpa [hs]
        simpa [restrictTo, deleteGenerators, hs', Uses, hs] using
          And.intro hs ih
      · have hs' : signedBase s ∈ Finset.univ \ A := by
          simp [hs]
        simpa [restrictTo, deleteGenerators, hs', Uses] using ih

end LabelWord

variable {ι Γ : Type*} [Fintype ι] [DecidableEq ι] [Group Γ]

/-- If Γ is k-retractable and A has at most k labels, then the
ACTUAL subgroup generated by A, made into a labelled group
by setting every generator outside A to 1, is globally
retractable on the entire ambient generator alphabet.

This is the local-to-global group bridge necessary to
apply the source's full-retractability Cayley geometry to
rank-two subalphabet groups of merely 2-retractable H₁. -/
theorem retractable_trivialCompletionGenerator_of_kRetractable
    (gen : ι → Γ) (k : ℕ)
    (hret : KRetractable gen k)
    (A : Finset ι) (hA : A.card ≤ k) :
    Retractable (trivialCompletionGenerator gen A) := by
  intro a p q hpq
  have hEval : PSTS.SignedWord.evalGroup gen
        (LabelWord.restrictTo A p) =
      PSTS.SignedWord.evalGroup gen
        (LabelWord.restrictTo A q) := by
    have h := congrArg
      (fun x : generatedSubgroup gen A => (x : Γ)) hpq
    simpa only [coe_evalGroup_trivialCompletionGenerator] using h
  have hErase :
      PSTS.SignedWord.evalGroup gen
          (LabelWord.eraseGenerator a (LabelWord.restrictTo A p)) =
        PSTS.SignedWord.evalGroup gen
          (LabelWord.eraseGenerator a (LabelWord.restrictTo A q)) :=
    hret A hA a
      (LabelWord.restrictTo A p) (LabelWord.restrictTo A q)
      (LabelWord.uses_restrictTo A p)
      (LabelWord.uses_restrictTo A q) hEval
  apply Subtype.ext
  change
    ((PSTS.SignedWord.evalGroup
       (trivialCompletionGenerator gen A)
       (LabelWord.eraseGenerator a p) :
          generatedSubgroup gen A) : Γ) =
      ((PSTS.SignedWord.evalGroup
       (trivialCompletionGenerator gen A)
       (LabelWord.eraseGenerator a q) :
          generatedSubgroup gen A) : Γ)
  rw [coe_evalGroup_trivialCompletionGenerator,
    coe_evalGroup_trivialCompletionGenerator,
    LabelWord.restrictTo_eraseGenerator,
    LabelWord.restrictTo_eraseGenerator]
  exact hErase

end ABO
end PSTSEPPA
