import PSTSEPPA.ABO.KRetractableCosetIntersections
import PSTSEPPA.ABO.RankTwoThreeFamilyTwoRetractable

/-!
# Use rank-bounded retractability for genuine local rank-two ABO stages

An intermediate Section-5 labelled group is not known globally
retractable: source corrected Proposition 5.4 supplies only
rank-bounded retractability. The actual subgroup generated by a
rank-two alphabet, completed by trivial generators on all other
labels, is nevertheless a GLOBAL retractable labelled group by
`retractable_trivialCompletionGenerator_of_kRetractable`.

We prove a second missing interface fact: this labelled subgroup is
generated by its *entire* completed generator map (also when the
original ambient group is not generated). Consequently all existing
rank-two three-family stage/cover theorems apply literally to a
Cayley skeleton over the true local subgroup.

The output is a concrete surjective 1-stable finite (for finite Γ)
cover whose group is 2-retractable. It is a LOCAL RANK-TWO stage over
Γ[A], not the as-yet-unconstructed whole H₁-cover/Z₁ catalogue or
the full global G₂→H₁ quotient.
-/

namespace PSTSEPPA
namespace ABO

variable {ι Γ : Type*} [Fintype ι] [DecidableEq ι] [Group Γ]

/-- The actual labelled subgroup Γ[A], with all generators outside
A sent to the identity, is generated by its completed alphabet.
The ambient Γ need not be generated by the original labels. -/
theorem isGenerated_trivialCompletionGenerator
    (gen : ι → Γ) (A : Finset ι) :
    IsGenerated (trivialCompletionGenerator gen A) := by
  classical
  unfold IsGenerated
  apply top_unique
  intro x _
  obtain ⟨w, hwA, hwVal⟩ :=
    exists_word_uses_eq_of_mem_generatedSubgroup gen A x.property
  have hEval :
      PSTS.SignedWord.evalGroup
        (trivialCompletionGenerator gen A) w = x := by
    apply Subtype.ext
    change
      ((PSTS.SignedWord.evalGroup
        (trivialCompletionGenerator gen A) w :
        generatedSubgroup gen A) : Γ) = x.1
    rw [coe_evalGroup_trivialCompletionGenerator,
      LabelWord.restrictTo_eq_self_of_uses A w hwA]
    exact hwVal
  have hUniv :
      generatedSubgroup (trivialCompletionGenerator gen A)
        Finset.univ ≤
        Subgroup.closure (Set.range (trivialCompletionGenerator gen A)) := by
    unfold generatedSubgroup
    apply (Subgroup.closure_le _).2
    rintro _ ⟨i, rfl⟩
    apply Subgroup.subset_closure
    exact ⟨i.1, rfl⟩
  have hmem :
      PSTS.SignedWord.evalGroup
        (trivialCompletionGenerator gen A) w ∈
          Subgroup.closure (Set.range (trivialCompletionGenerator gen A)) :=
    hUniv (evalGroup_mem_generatedSubgroup_of_uses
      (trivialCompletionGenerator gen A) Finset.univ
      (LabelWord.uses_univ w))
  rwa [hEval] at hmem

/-- For every ≤k-letter local subgroup, the completed generator
map is BOTH generated and fully retractable, under only the
k-retractability hypothesis on the original labelled group. -/
theorem generated_retractable_local_group
    (gen : ι → Γ) (k : ℕ)
    (hret : KRetractable gen k)
    (A : Finset ι) (hA : A.card ≤ k) :
    IsGenerated (trivialCompletionGenerator gen A) ∧
      Retractable (trivialCompletionGenerator gen A) :=
  ⟨isGenerated_trivialCompletionGenerator gen A,
    retractable_trivialCompletionGenerator_of_kRetractable gen k hret A hA⟩

namespace CayleySubgraphSpec

variable {gen : ι → Γ} {A : Finset ι}
variable (K : CayleySubgraphSpec (trivialCompletionGenerator gen A) A)

/-- Actual 1-stability of the synchronized cover of all three
rank-two stage subfamilies over the local rank-two subgroup.
Unlike the earlier theorem, it makes NO global retractability
assumption on the original ambient labelled Γ. -/
theorem rankTwoLocalThreeFamilyCover_oneStable
    (hcard : A.card = 2) (hret : KRetractable gen 2) :
    (K.rankTwoThreeFamilyCoverQuotient hcard
      (isGenerated_trivialCompletionGenerator gen A)
      (retractable_trivialCompletionGenerator_of_kRetractable
        gen 2 hret A hcard.le)).KStable 1 := by
  exact K.rankTwoThreeFamilyCoverQuotient_oneStable
    hcard (isGenerated_trivialCompletionGenerator gen A)
    (retractable_trivialCompletionGenerator_of_kRetractable
      gen 2 hret A hcard.le)

/-- The actual synchronized group over Γ[A] is 2-retractable,
under only rank-TWO retractability of the ORIGINAL Γ. This uses
the already certified genuine three-family stable cover, not a
hypothetical group stage or arbitrary generator-preserving map. -/
theorem rankTwoLocalThreeFamilyCover_twoRetractable
    (hcard : A.card = 2) (hret : KRetractable gen 2) :
    KRetractable
      (SynchronizedProduct.generator
        (trivialCompletionGenerator gen A)
        (K.rankTwoThreeFamilyStage hcard
          (isGenerated_trivialCompletionGenerator gen A)
          (retractable_trivialCompletionGenerator_of_kRetractable
            gen 2 hret A hcard.le)).transitionSubgroupGenerator)
      2 := by
  exact K.rankTwoThreeFamilyCover_twoRetractable
    hcard (isGenerated_trivialCompletionGenerator gen A)
    (retractable_trivialCompletionGenerator_of_kRetractable
      gen 2 hret A hcard.le)

variable [Finite Γ]

/-- Finiteness holds for the TRUE synchronized rank-two stage over
the generated subgroup Γ[A], not just the original ambient group. -/
theorem finite_rankTwoLocalThreeFamilyCover
    (hcard : A.card = 2) (hret : KRetractable gen 2) :
    Finite (K.rankTwoThreeFamilyCover hcard
      (isGenerated_trivialCompletionGenerator gen A)
      (retractable_trivialCompletionGenerator_of_kRetractable
        gen 2 hret A hcard.le)) := by
  exact K.finite_rankTwoThreeFamilyCover
    hcard (isGenerated_trivialCompletionGenerator gen A)
    (retractable_trivialCompletionGenerator_of_kRetractable
      gen 2 hret A hcard.le)

end CayleySubgraphSpec
end ABO
end PSTSEPPA
