import PSTSEPPA.ABO.RankDetectorGroup
import PSTSEPPA.ABO.StageStabilityWordKernel
import PSTSEPPA.ABO.SynchronizedGeneratedGroup

/-!
# Elementary finite group rank lift via ALL bounded-subalphabet detectors

There is an explicit algebraic construction for every k, avoiding
any assumed global retractability of the original Γ.

For finite labelled gen : ι → Γ, form the dependent product
  D_k = Π_{A ⊆ ι, |A|≤k} Γ[A],
where each detector has all generators outside A set to identity.
Synchronize Γ with the TRUE labelled generator family of D_k:
  H_{k+1} := ⟨ (gen(i), detector(i)) : i∈ι ⟩ ≤ Γ × D_k.

Two separate (and carefully scoped) conclusions hold:

1. H_{k+1} is (k+1)-RETRACTABLE for EVERY Γ, without requiring
   Γ to be k-retractable. When erasing a from a word on at most
   k+1 labels, the Γ-coordinate is detected by A\{a}, while each
   D_k-coordinate B is detected by the lower coordinate B\{a}.
2. IF Γ is k-retractable and generated by gen, the actual quotient
   H_{k+1} ↠ Γ is k-STABLE: all ≤k-label Γ-relations vanish in
   every detector coordinate by the bounded restriction lemma.

For finite Γ the actual generated subgroup H_{k+1} is finite.
This gives an elementary algebraic rank lift. It does NOT replace
the graph-cover, bridge-freeness, cluster, or reflecting-group
requirements of corrected ABO I.
-/

namespace PSTSEPPA
namespace ABO

variable {ι Γ : Type*} [Fintype ι] [DecidableEq ι] [Group Γ]

/-- TRUE synchronously generated group, not the whole product
Γ × D_k. It has exactly the distinguished generator pairs. -/
abbrev RankDetectorSynchronizedCover (gen : ι → Γ) (k : ℕ) :=
  SynchronizedProduct.subgroup gen (rankDetectorGenerator gen k)

/-- The actual labelled synchronous generators, with no presumed
freeness, injectivity, or nontriviality of individual labels. -/
abbrev rankDetectorSynchronizedGenerator (gen : ι → Γ) (k : ℕ) :=
  SynchronizedProduct.generator gen (rankDetectorGenerator gen k)

/-- The true synchronous generator family generates its group. -/
theorem rankDetectorSynchronized_isGenerated
    (gen : ι → Γ) (k : ℕ) :
    IsGenerated (rankDetectorSynchronizedGenerator gen k) :=
  SynchronizedProduct.generator_isGenerated gen
    (rankDetectorGenerator gen k)

/-- The actual generator-preserving surjective labelled projection
onto Γ, assuming the source alphabet generates Γ. -/
def rankDetectorSynchronizedQuotient
    (gen : ι → Γ) (k : ℕ) (hgen : IsGenerated gen) :
    LabelledGroupQuotient
      (rankDetectorSynchronizedGenerator gen k) gen :=
  SynchronizedProduct.fstQuotient gen
    (rankDetectorGenerator gen k) hgen

/-- The central direct algebraic rank lift. The generated synchronous
group is (k+1)-retractable even when Γ fails k-retractability.

The proof works on arbitrary PAIRS of equal signed words and checks
BOTH coordinates; it does not silently substitute a weaker
single-kernel test. -/
theorem rankDetectorSynchronized_kSuccRetractable
    (gen : ι → Γ) (k : ℕ) :
    KRetractable (rankDetectorSynchronizedGenerator gen k) (k + 1) := by
  intro C hC a p q hp hq hpq
  by_cases ha : a ∈ C
  · have hB : (C.erase a).card ≤ k :=
      Nat.lt_succ_iff.mp
        (lt_of_lt_of_le (Finset.card_erase_lt_of_mem ha) hC)
    let dB : RankDetectorIndex ι k := ⟨C.erase a, hB⟩
    have hD :
        PSTS.SignedWord.evalGroup (rankDetectorGenerator gen k) p =
          PSTS.SignedWord.evalGroup (rankDetectorGenerator gen k) q := by
      have h := congrArg
        (SynchronizedProduct.sndHom gen (rankDetectorGenerator gen k)) hpq
      simpa only [SynchronizedProduct.sndHom_evalGroup] using h
    have hAt :
        (PSTS.SignedWord.evalGroup (rankDetectorGenerator gen k) p) dB =
          (PSTS.SignedWord.evalGroup (rankDetectorGenerator gen k) q) dB :=
      congrArg (fun t : RankDetectorGroup gen k => t dB) hD
    have hAtVal :
        (((PSTS.SignedWord.evalGroup (rankDetectorGenerator gen k) p)
          dB : generatedSubgroup gen dB.1) : Γ) =
        (((PSTS.SignedWord.evalGroup (rankDetectorGenerator gen k) q)
          dB : generatedSubgroup gen dB.1) : Γ) :=
      congrArg (fun t : generatedSubgroup gen dB.1 => (t : Γ)) hAt
    have hGammaErase :
        PSTS.SignedWord.evalGroup gen (LabelWord.eraseGenerator a p) =
          PSTS.SignedWord.evalGroup gen (LabelWord.eraseGenerator a q) := by
      calc
        PSTS.SignedWord.evalGroup gen (LabelWord.eraseGenerator a p) =
            PSTS.SignedWord.evalGroup gen
              (LabelWord.restrictTo (C.erase a) p) :=
          congrArg (PSTS.SignedWord.evalGroup gen)
            (LabelWord.eraseGenerator_eq_restrictTo_erase_of_uses C a p hp)
        _ = (((PSTS.SignedWord.evalGroup (rankDetectorGenerator gen k) p)
              dB : generatedSubgroup gen dB.1) : Γ) :=
          (coe_evalGroup_rankDetector gen k p dB).symm
        _ = (((PSTS.SignedWord.evalGroup (rankDetectorGenerator gen k) q)
              dB : generatedSubgroup gen dB.1) : Γ) := hAtVal
        _ = PSTS.SignedWord.evalGroup gen
              (LabelWord.restrictTo (C.erase a) q) :=
          coe_evalGroup_rankDetector gen k q dB
        _ = PSTS.SignedWord.evalGroup gen (LabelWord.eraseGenerator a q) :=
          congrArg (PSTS.SignedWord.evalGroup gen)
            (LabelWord.eraseGenerator_eq_restrictTo_erase_of_uses C a q hq).symm
    have hDetectorErase :
        PSTS.SignedWord.evalGroup
            (rankDetectorGenerator gen k) (LabelWord.eraseGenerator a p) =
          PSTS.SignedWord.evalGroup
            (rankDetectorGenerator gen k) (LabelWord.eraseGenerator a q) := by
      apply funext
      intro j
      apply Subtype.ext
      have hJ :
          (PSTS.SignedWord.evalGroup (rankDetectorGenerator gen k) p)
              (j.erase a) =
            (PSTS.SignedWord.evalGroup (rankDetectorGenerator gen k) q)
              (j.erase a) :=
        congrArg (fun t : RankDetectorGroup gen k => t (j.erase a)) hD
      have hJVal :=
        congrArg
          (fun t : generatedSubgroup gen (j.erase a).1 => (t : Γ)) hJ
      calc
        (((PSTS.SignedWord.evalGroup (rankDetectorGenerator gen k)
            (LabelWord.eraseGenerator a p)) j :
              generatedSubgroup gen j.1) : Γ) =
          (((PSTS.SignedWord.evalGroup (rankDetectorGenerator gen k) p)
            (j.erase a) : generatedSubgroup gen (j.erase a).1) : Γ) :=
          coe_evalGroup_rankDetector_erase gen k j a p
        _ = (((PSTS.SignedWord.evalGroup (rankDetectorGenerator gen k) q)
            (j.erase a) : generatedSubgroup gen (j.erase a).1) : Γ) := hJVal
        _ = (((PSTS.SignedWord.evalGroup (rankDetectorGenerator gen k)
            (LabelWord.eraseGenerator a q)) j :
              generatedSubgroup gen j.1) : Γ) :=
          (coe_evalGroup_rankDetector_erase gen k j a q).symm
    apply Subtype.ext
    apply Prod.ext
    · change SynchronizedProduct.fstHom gen
          (rankDetectorGenerator gen k)
          (PSTS.SignedWord.evalGroup
            (rankDetectorSynchronizedGenerator gen k)
            (LabelWord.eraseGenerator a p)) =
        SynchronizedProduct.fstHom gen
          (rankDetectorGenerator gen k)
          (PSTS.SignedWord.evalGroup
            (rankDetectorSynchronizedGenerator gen k)
            (LabelWord.eraseGenerator a q))
      rw [SynchronizedProduct.fstHom_evalGroup,
        SynchronizedProduct.fstHom_evalGroup]
      exact hGammaErase
    · change SynchronizedProduct.sndHom gen
          (rankDetectorGenerator gen k)
          (PSTS.SignedWord.evalGroup
            (rankDetectorSynchronizedGenerator gen k)
            (LabelWord.eraseGenerator a p)) =
        SynchronizedProduct.sndHom gen
          (rankDetectorGenerator gen k)
          (PSTS.SignedWord.evalGroup
            (rankDetectorSynchronizedGenerator gen k)
            (LabelWord.eraseGenerator a q))
      rw [SynchronizedProduct.sndHom_evalGroup,
        SynchronizedProduct.sndHom_evalGroup]
      exact hDetectorErase
  · have hc : C.erase a = C := Finset.erase_eq_of_not_mem ha
    have hpNo : LabelWord.eraseGenerator a p = p := by
      rw [LabelWord.eraseGenerator_eq_restrictTo_erase_of_uses C a p hp,
        hc, LabelWord.restrictTo_eq_self_of_uses C p hp]
    have hqNo : LabelWord.eraseGenerator a q = q := by
      rw [LabelWord.eraseGenerator_eq_restrictTo_erase_of_uses C a q hq,
        hc, LabelWord.restrictTo_eq_self_of_uses C q hq]
    simpa [hpNo, hqNo] using hpq

/-- When Γ is already k-retractable, the ACTUAL finite-rank
synchronous quotient preserves all relations of rank ≤k.
The proof checks every true detector coordinate via the
bounded group-word restriction theorem. -/
theorem rankDetectorSynchronizedQuotient_kStable
    (gen : ι → Γ) (k : ℕ)
    (hgen : IsGenerated gen) (hret : KRetractable gen k) :
    (rankDetectorSynchronizedQuotient gen k hgen).KStable k := by
  apply (rankDetectorSynchronizedQuotient gen k hgen).kStable_of_word_kernel k
  intro C hC w hw hval
  have hDetector :
      PSTS.SignedWord.evalGroup (rankDetectorGenerator gen k) w = 1 := by
    apply funext
    intro j
    have hSrc :
        PSTS.SignedWord.evalGroup gen w =
          PSTS.SignedWord.evalGroup gen ([] : LabelWord ι) := by
      simpa using hval
    have hRestrict :=
      KRetractable.restrictTo_eq_of_uses
        gen hret C hC j.1 w [] hw (LabelWord.uses_nil C) hSrc
    have hNil : LabelWord.restrictTo j.1 ([] : LabelWord ι) = [] := rfl
    rw [hNil] at hRestrict
    apply Subtype.ext
    change
      (((PSTS.SignedWord.evalGroup (rankDetectorGenerator gen k) w) j :
        generatedSubgroup gen j.1) : Γ) = 1
    rw [coe_evalGroup_rankDetector]
    simpa using hRestrict
  apply Subtype.ext
  apply Prod.ext
  · change SynchronizedProduct.fstHom gen
        (rankDetectorGenerator gen k)
        (PSTS.SignedWord.evalGroup
          (rankDetectorSynchronizedGenerator gen k) w) = (1 : Γ)
    exact (SynchronizedProduct.fstHom_evalGroup gen
      (rankDetectorGenerator gen k) w).trans hval
  · change SynchronizedProduct.sndHom gen
        (rankDetectorGenerator gen k)
        (PSTS.SignedWord.evalGroup
          (rankDetectorSynchronizedGenerator gen k) w) =
            (1 : RankDetectorGroup gen k)
    exact (SynchronizedProduct.sndHom_evalGroup gen
      (rankDetectorGenerator gen k) w).trans hDetector

variable [Finite Γ]

/-- The actual rank-lift group is finite for finite Γ and alphabet,
including all signed labels and all dependent detector coordinates. -/
theorem finite_rankDetectorSynchronizedCover
    (gen : ι → Γ) (k : ℕ) :
    Finite (RankDetectorSynchronizedCover gen k) := by
  classical
  letI : Finite (RankDetectorGroup gen k) :=
    finite_rankDetectorGroup gen k
  letI : Fintype Γ := Fintype.ofFinite _
  letI : Fintype (RankDetectorGroup gen k) := Fintype.ofFinite _
  infer_instance

end ABO
end PSTSEPPA
