import PSTSEPPA.ABO.RetractabilityCover

/-!
# Retractions from retractability

The reverse direction of ABO Proposition 3.3.  Retractability makes
subalphabet restriction well defined on group values.  We package the induced
map as a group retraction, then turn it into the canonical Cayley graph cover
of the trivial completion.
-/

namespace PSTSEPPA
namespace ABO

open PSTS

variable {ι Γ : Type*} [Fintype ι] [DecidableEq ι] [Group Γ]

/-- A chosen signed-word representative of a group element. -/
noncomputable def wordRep
    (gen : ι → Γ) (hgen : IsGenerated gen) (g : Γ) : LabelWord ι :=
  Classical.choose (hgen.exists_evalGroup_eq g)

@[simp]
theorem evalGroup_wordRep
    (gen : ι → Γ) (hgen : IsGenerated gen) (g : Γ) :
    PSTS.SignedWord.evalGroup gen (wordRep gen hgen g) = g :=
  Classical.choose_spec (hgen.exists_evalGroup_eq g)

/-- Source-equal words have equal values in every trivial completion when the
ambient labelled group is retractable. -/
theorem evalGroup_trivialCompletion_eq_of_eq
    {gen : ι → Γ} (hret : Retractable gen) (A : Finset ι)
    {p q : LabelWord ι}
    (hpq :
      PSTS.SignedWord.evalGroup gen p =
        PSTS.SignedWord.evalGroup gen q) :
    PSTS.SignedWord.evalGroup (trivialCompletionGenerator gen A) p =
      PSTS.SignedWord.evalGroup (trivialCompletionGenerator gen A) q := by
  apply Subtype.ext
  change
    ((PSTS.SignedWord.evalGroup (trivialCompletionGenerator gen A) p :
        generatedSubgroup gen A) : Γ) =
      ((PSTS.SignedWord.evalGroup (trivialCompletionGenerator gen A) q :
        generatedSubgroup gen A) : Γ)
  rw [coe_evalGroup_trivialCompletionGenerator,
    coe_evalGroup_trivialCompletionGenerator]
  exact hret.restrictTo_eq A hpq

/-- The retraction onto the subgroup generated by a subalphabet. -/
noncomputable def retractHom
    (gen : ι → Γ) (hgen : IsGenerated gen) (hret : Retractable gen)
    (A : Finset ι) :
    Γ →* generatedSubgroup gen A where
  toFun g :=
    PSTS.SignedWord.evalGroup
      (trivialCompletionGenerator gen A)
      (wordRep gen hgen g)
  map_one' := by
    have h := evalGroup_trivialCompletion_eq_of_eq
      (gen := gen) hret A
      (p := wordRep gen hgen 1)
      (q := ([] : LabelWord ι))
      (by simp)
    simpa using h
  map_mul' x y := by
    have hsource :
        PSTS.SignedWord.evalGroup gen (wordRep gen hgen (x * y)) =
          PSTS.SignedWord.evalGroup gen
            (wordRep gen hgen x ++ wordRep gen hgen y) := by
      simp
    have h := evalGroup_trivialCompletion_eq_of_eq
      (gen := gen) hret A hsource
    simpa using h

/-- The retraction sends every labelled generator to the corresponding
trivial-completion generator. -/
@[simp]
theorem retractHom_generator
    (gen : ι → Γ) (hgen : IsGenerated gen) (hret : Retractable gen)
    (A : Finset ι) (i : ι) :
    retractHom gen hgen hret A (gen i) =
      trivialCompletionGenerator gen A i := by
  change
    PSTS.SignedWord.evalGroup
        (trivialCompletionGenerator gen A)
        (wordRep gen hgen (gen i)) =
      trivialCompletionGenerator gen A i
  have hsource :
      PSTS.SignedWord.evalGroup gen (wordRep gen hgen (gen i)) =
        PSTS.SignedWord.evalGroup gen [PSTS.SignedLetter.pos i] := by
    simp
  have h := evalGroup_trivialCompletion_eq_of_eq
    (gen := gen) hret A hsource
  simpa using h

/-- The retraction is literally the identity on the generated subgroup. -/
theorem retractHom_on_generatedSubgroup
    (gen : ι → Γ) (hgen : IsGenerated gen) (hret : Retractable gen)
    (A : Finset ι) (x : generatedSubgroup gen A) :
    retractHom gen hgen hret A x.1 = x := by
  have hfix :
      ∀ g : Γ, g ∈ generatedSubgroup gen A →
        ((retractHom gen hgen hret A g :
            generatedSubgroup gen A) : Γ) = g := by
    intro g hg
    induction hg using Subgroup.closure_induction with
    | mem y hy =>
        rcases hy with ⟨i, rfl⟩
        rw [retractHom_generator]
        simp [trivialCompletionGenerator, i.property]
    | one =>
        simp
    | mul y z hy hz ihy ihz =>
        simp [ihy, ihz]
    | inv y hy ih =>
        simp [ih]
  apply Subtype.ext
  exact hfix x.1 x.2

/-- Hence the retraction is onto the subalphabet subgroup. -/
theorem retractHom_surjective
    (gen : ι → Γ) (hgen : IsGenerated gen) (hret : Retractable gen)
    (A : Finset ι) :
    Function.Surjective (retractHom gen hgen hret A) := by
  intro x
  exact ⟨x.1, retractHom_on_generatedSubgroup gen hgen hret A x⟩

/-- A generator-preserving group homomorphism induces a labelled morphism of
the corresponding complete Cayley graphs. -/
noncomputable def cayleyHomOfGroupHom
    {Δ : Type*} [Group Δ]
    (genΓ : ι → Γ) (genΔ : ι → Δ)
    (φ : Γ →* Δ)
    (hφ : ∀ i, φ (genΓ i) = genΔ i) :
    LabelledGraphHom
      (cayleyGraph genΓ).toEGraph.toLabelledGraph
      (cayleyGraph genΔ).toEGraph.toLabelledGraph where
  onVertex := φ
  onEdge := fun e => (φ e.1, e.2)
  map_source := by
    rintro ⟨g, s⟩
    rfl
  map_label := by
    rintro ⟨g, s⟩
    rfl
  map_inv := by
    rintro ⟨g, s⟩
    apply Prod.ext
    · change
        φ ((cayleyGraph genΓ).target (g, s)) =
          (cayleyGraph genΔ).target (φ g, s)
      rw [cayleyGraph.target_eq_mul_evalGroupLetter,
        cayleyGraph.target_eq_mul_evalGroupLetter]
      cases s with
      | pos i =>
          simp [hφ]
      | neg i =>
          simp [hφ]
    · rfl

/-- Retractability produces a based surjective Cayley cover of every trivial
subalphabet completion. -/
noncomputable def trivialCompletionCover_of_retractable
    (gen : ι → Γ) (hgen : IsGenerated gen) (hret : Retractable gen)
    (A : Finset ι) :
    TrivialCompletionCover gen A where
  hom :=
    cayleyHomOfGroupHom
      gen
      (trivialCompletionGenerator gen A)
      (retractHom gen hgen hret A)
      (retractHom_generator gen hgen hret A)
  map_one := by
    simp [cayleyHomOfGroupHom]
  vertex_surjective :=
    retractHom_surjective gen hgen hret A

/-- Existence, rather than chosen data, of a trivial-completion
cover. -/
def HasTrivialCompletionCover (gen : ι → Γ) (A : Finset ι) : Prop :=
  Nonempty (TrivialCompletionCover gen A)

/-- ABO Proposition 3.3, in based form.

For a labelled family which generates the ambient group, retractability is
equivalent to existence of a based surjective Cayley cover onto every trivial
subalphabet completion. -/
theorem retractable_iff_trivialCompletionCovers
    (gen : ι → Γ) (hgen : IsGenerated gen) :
    Retractable gen ↔
      ∀ A : Finset ι, HasTrivialCompletionCover gen A := by
  constructor
  · intro hret A
    exact ⟨trivialCompletionCover_of_retractable gen hgen hret A⟩
  · intro hcovers
    exact retractable_of_trivialCompletionCovers gen
      (fun A => Classical.choice (hcovers A))

end ABO
end PSTSEPPA
