import PSTSEPPA.ABO.CanonicalCover
import Mathlib.Algebra.Group.Subgroup.Lattice

/-!
# Retractability for finite labelled groups

This file formalizes the algebra behind ABO Definition 3.2 and prepares the
exact Proposition 3.3 equivalence.

The alphabet is finite.  Words are evaluated in the same chronological
left-to-right convention already used throughout T1/T2 and the ABO transition
group layer.
-/

namespace PSTSEPPA
namespace ABO

open PSTS

/-- Forget the sign of a signed generator. -/
def signedBase {ι : Type*} : SignedLabel ι → ι
  | .pos i => i
  | .neg i => i

@[simp]
theorem signedBase_pos {ι : Type*} (i : ι) :
    signedBase (PSTS.SignedLetter.pos i) = i :=
  rfl

@[simp]
theorem signedBase_neg {ι : Type*} (i : ι) :
    signedBase (PSTS.SignedLetter.neg i) = i :=
  rfl

@[simp]
theorem signedBase_inv {ι : Type*} (s : SignedLabel ι) :
    signedBase (PSTS.SignedLetter.inv s) = signedBase s := by
  cases s <;> rfl

namespace LabelWord

variable {ι : Type*} [DecidableEq ι]

/-- Delete every occurrence of generators whose underlying positive letter lies
in `D`.  Both positive and negative occurrences are deleted. -/
def deleteGenerators (D : Finset ι) : LabelWord ι → LabelWord ι
  | [] => []
  | s :: w =>
      if signedBase s ∈ D then
        deleteGenerators D w
      else
        s :: deleteGenerators D w

@[simp]
theorem deleteGenerators_nil (D : Finset ι) :
    deleteGenerators D ([] : LabelWord ι) = [] :=
  rfl

theorem deleteGenerators_cons (D : Finset ι) (s : SignedLabel ι)
    (w : LabelWord ι) :
    deleteGenerators D (s :: w) =
      if signedBase s ∈ D then
        deleteGenerators D w
      else
        s :: deleteGenerators D w :=
  rfl

@[simp]
theorem deleteGenerators_empty (w : LabelWord ι) :
    deleteGenerators ∅ w = w := by
  induction w with
  | nil =>
      rfl
  | cons s w ih =>
      simp [deleteGenerators, ih]

/-- Deleting a union of generators can be done one generator at a time. -/
theorem deleteGenerators_insert (a : ι) (D : Finset ι)
    (w : LabelWord ι) :
    deleteGenerators (insert a D) w =
      deleteGenerators D (deleteGenerators {a} w) := by
  induction w with
  | nil =>
      rfl
  | cons s w ih =>
      by_cases ha : signedBase s = a
      · simp [deleteGenerators, ha, ih]
      · by_cases hD : signedBase s ∈ D
        · simp [deleteGenerators, ha, hD, ih]
        · simp [deleteGenerators, ha, hD, ih]

/-- ABO deletion `p_{a -> 1}`. -/
def eraseGenerator (a : ι) (w : LabelWord ι) : LabelWord ι :=
  deleteGenerators {a} w

/-- Restrict a word to a finite subalphabet `A`. -/
def restrictTo [Fintype ι] (A : Finset ι) (w : LabelWord ι) :
    LabelWord ι :=
  deleteGenerators (Finset.univ \ A) w

@[simp]
theorem restrictTo_univ [Fintype ι] (w : LabelWord ι) :
    restrictTo Finset.univ w = w := by
  simp [restrictTo]

end LabelWord

section GroupWords

variable {ι Γ : Type*} [Fintype ι] [DecidableEq ι] [Group Γ]

/-- The subgroup generated by the letters in `A`. -/
def generatedSubgroup (gen : ι → Γ) (A : Finset ι) : Subgroup Γ :=
  Subgroup.closure
    (Set.range (fun i : {i : ι // i ∈ A} => gen i.1))

theorem generator_mem_generatedSubgroup
    (gen : ι → Γ) (A : Finset ι) {i : ι} (hi : i ∈ A) :
    gen i ∈ generatedSubgroup gen A := by
  apply Subgroup.subset_closure
  exact ⟨⟨i, hi⟩, rfl⟩

/-- Generator family for the trivial completion of the Cayley graph of
`generatedSubgroup gen A`: letters in `A` act as usual and letters outside
`A` act by the identity. -/
def trivialCompletionGenerator (gen : ι → Γ) (A : Finset ι) :
    ι → generatedSubgroup gen A :=
  fun i =>
    if hi : i ∈ A then
      ⟨gen i, generator_mem_generatedSubgroup gen A hi⟩
    else
      1

@[simp]
theorem trivialCompletionGenerator_mem
    (gen : ι → Γ) (A : Finset ι) {i : ι} (hi : i ∈ A) :
    ((trivialCompletionGenerator gen A i :
        generatedSubgroup gen A) : Γ) = gen i := by
  simp [trivialCompletionGenerator, hi]

@[simp]
theorem trivialCompletionGenerator_not_mem
    (gen : ι → Γ) (A : Finset ι) {i : ι} (hi : i ∉ A) :
    trivialCompletionGenerator gen A i = 1 := by
  simp [trivialCompletionGenerator, hi]

/-- Evaluating a word in the trivial completion agrees, after coercion back to
the ambient group, with evaluating the word after deleting all letters outside
`A`. -/
theorem coe_evalGroup_trivialCompletionGenerator
    (gen : ι → Γ) (A : Finset ι) (w : LabelWord ι) :
    ((PSTS.SignedWord.evalGroup
        (trivialCompletionGenerator gen A) w :
          generatedSubgroup gen A) : Γ) =
      PSTS.SignedWord.evalGroup gen (LabelWord.restrictTo A w) := by
  induction w with
  | nil =>
      rfl
  | cons s w ih =>
      cases s with
      | pos i =>
          by_cases hi : i ∈ A
          · simp [LabelWord.restrictTo, LabelWord.deleteGenerators,
              trivialCompletionGenerator, hi, ih]
          · simp [LabelWord.restrictTo, LabelWord.deleteGenerators,
              trivialCompletionGenerator, hi, ih]
      | neg i =>
          by_cases hi : i ∈ A
          · simp [LabelWord.restrictTo, LabelWord.deleteGenerators,
              trivialCompletionGenerator, hi, ih]
          · simp [LabelWord.restrictTo, LabelWord.deleteGenerators,
              trivialCompletionGenerator, hi, ih]

/-- The source definition of retractability: every word equality survives
deletion of all occurrences of one generator and its formal inverse. -/
def Retractable (gen : ι → Γ) : Prop :=
  ∀ a : ι, ∀ p q : LabelWord ι,
    PSTS.SignedWord.evalGroup gen p =
        PSTS.SignedWord.evalGroup gen q →
      PSTS.SignedWord.evalGroup gen (LabelWord.eraseGenerator a p) =
        PSTS.SignedWord.evalGroup gen (LabelWord.eraseGenerator a q)

/-- A retractable group preserves word equalities under deletion of any finite
set of generators. -/
theorem Retractable.deleteGenerators_eq
    {gen : ι → Γ} (hret : Retractable gen)
    (D : Finset ι) {p q : LabelWord ι}
    (hpq :
      PSTS.SignedWord.evalGroup gen p =
        PSTS.SignedWord.evalGroup gen q) :
    PSTS.SignedWord.evalGroup gen (LabelWord.deleteGenerators D p) =
      PSTS.SignedWord.evalGroup gen (LabelWord.deleteGenerators D q) := by
  induction D using Finset.induction_on generalizing p q with
  | empty =>
      simpa using hpq
  | @insert a D ha ih =>
      rw [LabelWord.deleteGenerators_insert, LabelWord.deleteGenerators_insert]
      apply ih
      simpa [LabelWord.eraseGenerator] using hret a p q hpq

/-- Hence retractability preserves word equalities after restriction to an
arbitrary subalphabet. -/
theorem Retractable.restrictTo_eq
    {gen : ι → Γ} (hret : Retractable gen)
    (A : Finset ι) {p q : LabelWord ι}
    (hpq :
      PSTS.SignedWord.evalGroup gen p =
        PSTS.SignedWord.evalGroup gen q) :
    PSTS.SignedWord.evalGroup gen (LabelWord.restrictTo A p) =
      PSTS.SignedWord.evalGroup gen (LabelWord.restrictTo A q) := by
  exact hret.deleteGenerators_eq (Finset.univ \ A) hpq

/-- The labelled family genuinely generates the ambient group. -/
def IsGenerated (gen : ι → Γ) : Prop :=
  Subgroup.closure (Set.range gen) = ⊤

/-- If the labelled family generates the group, every group element is the
value of a signed word. -/
theorem IsGenerated.exists_evalGroup_eq
    {gen : ι → Γ} (hgen : IsGenerated gen) (g : Γ) :
    ∃ w : LabelWord ι, PSTS.SignedWord.evalGroup gen w = g := by
  have hg : g ∈ Subgroup.closure (Set.range gen) := by
    rw [hgen]
    trivial
  induction hg using Subgroup.closure_induction with
  | mem x hx =>
      rcases hx with ⟨i, rfl⟩
      exact ⟨[PSTS.SignedLetter.pos i], by simp⟩
  | one =>
      exact ⟨[], by simp⟩
  | mul x y hx hy ihx ihy =>
      rcases ihx with ⟨p, hp⟩
      rcases ihy with ⟨q, hq⟩
      exact ⟨p ++ q, by simp [hp, hq]⟩
  | inv x hx ih =>
      rcases ih with ⟨p, hp⟩
      exact ⟨PSTS.SignedWord.inv p, by simp [hp]⟩

end GroupWords

end ABO
end PSTSEPPA
