import PSTSEPPA.ABO.RetractabilitySource

/-!
# Retractable subalphabet intersections

The first downstream consequence of ABO Proposition 3.3:
for a retractable labelled group, subgroups generated by subalphabets satisfy

  G[A] ∩ G[B] = G[A ∩ B].

This is the group-theoretic core used later to control coset and cluster
intersections.
-/

namespace PSTSEPPA
namespace ABO

variable {ι Γ : Type*} [Fintype ι] [DecidableEq ι] [Group Γ]

/-- Monotonicity of subalphabet-generated subgroups. -/
theorem generatedSubgroup_mono
    (gen : ι → Γ) {A B : Finset ι} (hAB : A ⊆ B) :
    generatedSubgroup gen A ≤ generatedSubgroup gen B := by
  unfold generatedSubgroup
  apply (Subgroup.closure_le _).2
  rintro _ ⟨i, rfl⟩
  apply Subgroup.subset_closure
  exact ⟨⟨i.1, hAB i.2⟩, rfl⟩

/-- Retracting a point of G[A] onto G[B] lands in G[A ∩ B]. -/
theorem retractHom_generatedSubgroup_mem_inter
    (gen : ι → Γ) (hgen : IsGenerated gen) (hret : Retractable gen)
    (A B : Finset ι) {x : Γ}
    (hxA : x ∈ generatedSubgroup gen A) :
    ((retractHom gen hgen hret B x : generatedSubgroup gen B) : Γ) ∈
      generatedSubgroup gen (A ∩ B) := by
  induction hxA using Subgroup.closure_induction with
  | mem y hy =>
      rcases hy with ⟨i, rfl⟩
      rw [retractHom_generator]
      by_cases hiB : i.1 ∈ B
      · rw [trivialCompletionGenerator_mem gen B hiB]
        apply generator_mem_generatedSubgroup
        exact Finset.mem_inter.mpr ⟨i.2, hiB⟩
      · rw [trivialCompletionGenerator_not_mem gen B hiB]
        exact (generatedSubgroup gen (A ∩ B)).one_mem
  | one =>
      simp
  | mul x y hx hy ihx ihy =>
      simpa using (generatedSubgroup gen (A ∩ B)).mul_mem ihx ihy
  | inv x hx ih =>
      simpa using (generatedSubgroup gen (A ∩ B)).inv_mem ih

/-- ABO's standard retractable subgroup-intersection identity. -/
theorem generatedSubgroup_inf
    (gen : ι → Γ) (hgen : IsGenerated gen) (hret : Retractable gen)
    (A B : Finset ι) :
    generatedSubgroup gen A ⊓ generatedSubgroup gen B =
      generatedSubgroup gen (A ∩ B) := by
  apply le_antisymm
  · intro x hx
    have hxA : x ∈ generatedSubgroup gen A := hx.1
    have hxB : x ∈ generatedSubgroup gen B := hx.2
    have himage :=
      retractHom_generatedSubgroup_mem_inter
        gen hgen hret A B hxA
    have hfix :
        retractHom gen hgen hret B x =
          (⟨x, hxB⟩ : generatedSubgroup gen B) :=
      retractHom_on_generatedSubgroup
        gen hgen hret B ⟨x, hxB⟩
    rw [hfix] at himage
    exact himage
  · intro x hx
    have hleft :
        generatedSubgroup gen (A ∩ B) ≤ generatedSubgroup gen A :=
      generatedSubgroup_mono gen (by
        intro i hi
        exact (Finset.mem_inter.mp hi).1)
    have hright :
        generatedSubgroup gen (A ∩ B) ≤ generatedSubgroup gen B :=
      generatedSubgroup_mono gen (by
        intro i hi
        exact (Finset.mem_inter.mp hi).2)
    exact ⟨hleft hx, hright hx⟩

end ABO
end PSTSEPPA
