import PSTSEPPA.ABO.Stability
import Mathlib.Data.Fintype.Prod

/-!
# Finite synchronized products of labelled groups

ABO Section 5 uses transition groups of finite disjoint unions
of complete E-graphs. Such a group acts componentwise, and its
labelled generators are synchronized tuples of the component
generators.

This module isolates the algebraic finite construction:
given two labelled groups Γ,Δ with the SAME edge alphabet ι,
take the subgroup of Γ×Δ generated by the pairs
  (genΓ(i), genΔ(i)).

It is finite when Γ and Δ are finite, and its coordinate maps
are LABELLED SURJECTIVE GROUP HOMOMORPHISMS as soon as each factor
is generated by its alphabet. Different generator labels may
act identically or trivially.

This is preparatory infrastructure for the finite stage induction.
It does not claim to construct the full reflecting group,
the cluster property, augmented coset extensions, or bridge-free
induction, and does not yet assert an isomorphism with a literal
graph disjoint-union transition group.
-/

namespace PSTSEPPA
namespace ABO

variable {ι Γ Δ : Type*}
variable [Fintype ι] [DecidableEq ι] [Group Γ] [Group Δ]

namespace SynchronizedProduct

/-- The subgroup of Γ×Δ generated synchronously by the
same positive label i in both coordinates. -/
def subgroup (genΓ : ι → Γ) (genΔ : ι → Δ) :
    Subgroup (Γ × Δ) :=
  Subgroup.closure (Set.range (fun i : ι => (genΓ i, genΔ i)))

/-- The actual positive generator of the synchronized group. -/
def generator (genΓ : ι → Γ) (genΔ : ι → Δ)
    (i : ι) : subgroup genΓ genΔ :=
  ⟨(genΓ i, genΔ i),
    Subgroup.subset_closure ⟨i, rfl⟩⟩

/-- The first coordinate is a homomorphism. -/
def fstHom (genΓ : ι → Γ) (genΔ : ι → Δ) :
    subgroup genΓ genΔ →* Γ where
  toFun x := x.1.1
  map_one' := rfl
  map_mul' _ _ := rfl

/-- The second coordinate is a homomorphism. -/
def sndHom (genΓ : ι → Γ) (genΔ : ι → Δ) :
    subgroup genΓ genΔ →* Δ where
  toFun x := x.1.2
  map_one' := rfl
  map_mul' _ _ := rfl

@[simp]
theorem fstHom_generator
    (genΓ : ι → Γ) (genΔ : ι → Δ) (i : ι) :
    fstHom genΓ genΔ (generator genΓ genΔ i) = genΓ i :=
  rfl

@[simp]
theorem sndHom_generator
    (genΓ : ι → Γ) (genΔ : ι → Δ) (i : ι) :
    sndHom genΓ genΔ (generator genΓ genΔ i) = genΔ i :=
  rfl

/-- Evaluating any signed word in the synchronized group and
projecting to Γ gives its literal Γ-value, in chronological order. -/
theorem fstHom_evalGroup
    (genΓ : ι → Γ) (genΔ : ι → Δ) (w : LabelWord ι) :
    fstHom genΓ genΔ
      (PSTS.SignedWord.evalGroup (generator genΓ genΔ) w) =
    PSTS.SignedWord.evalGroup genΓ w := by
  induction w with
  | nil => rfl
  | cons s w ih =>
      cases s with
      | pos i =>
          change genΓ i *
            fstHom genΓ genΔ
              (PSTS.SignedWord.evalGroup (generator genΓ genΔ) w) =
            genΓ i * PSTS.SignedWord.evalGroup genΓ w
          rw [ih]
      | neg i =>
          change (genΓ i)⁻¹ *
            fstHom genΓ genΔ
              (PSTS.SignedWord.evalGroup (generator genΓ genΔ) w) =
            (genΓ i)⁻¹ * PSTS.SignedWord.evalGroup genΓ w
          rw [ih]

/-- The symmetric projection formula for the second factor. -/
theorem sndHom_evalGroup
    (genΓ : ι → Γ) (genΔ : ι → Δ) (w : LabelWord ι) :
    sndHom genΓ genΔ
      (PSTS.SignedWord.evalGroup (generator genΓ genΔ) w) =
    PSTS.SignedWord.evalGroup genΔ w := by
  induction w with
  | nil => rfl
  | cons s w ih =>
      cases s with
      | pos i =>
          change genΔ i *
            sndHom genΓ genΔ
              (PSTS.SignedWord.evalGroup (generator genΓ genΔ) w) =
            genΔ i * PSTS.SignedWord.evalGroup genΔ w
          rw [ih]
      | neg i =>
          change (genΔ i)⁻¹ *
            sndHom genΓ genΔ
              (PSTS.SignedWord.evalGroup (generator genΓ genΔ) w) =
            (genΔ i)⁻¹ * PSTS.SignedWord.evalGroup genΔ w
          rw [ih]

/-- If the labelled alphabet generates Γ, the synchronized
subgroup projects SURJECTIVELY onto Γ. -/
theorem fstHom_surjective
    (genΓ : ι → Γ) (genΔ : ι → Δ)
    (hgenΓ : IsGenerated genΓ) :
    Function.Surjective (fstHom genΓ genΔ) := by
  intro x
  obtain ⟨w, hw⟩ := IsGenerated.exists_evalGroup_eq hgenΓ x
  refine ⟨PSTS.SignedWord.evalGroup (generator genΓ genΔ) w, ?_⟩
  exact (fstHom_evalGroup genΓ genΔ w).trans hw

/-- Likewise for the second component. -/
theorem sndHom_surjective
    (genΓ : ι → Γ) (genΔ : ι → Δ)
    (hgenΔ : IsGenerated genΔ) :
    Function.Surjective (sndHom genΓ genΔ) := by
  intro y
  obtain ⟨w, hw⟩ := IsGenerated.exists_evalGroup_eq hgenΔ y
  refine ⟨PSTS.SignedWord.evalGroup (generator genΓ genΔ) w, ?_⟩
  exact (sndHom_evalGroup genΓ genΔ w).trans hw

/-- The two component maps are actual labelled group quotients,
not merely set-theoretic surjections. -/
def fstQuotient
    (genΓ : ι → Γ) (genΔ : ι → Δ)
    (hgenΓ : IsGenerated genΓ) :
    LabelledGroupQuotient (generator genΓ genΔ) genΓ where
  hom := fstHom genΓ genΔ
  map_gen := fstHom_generator genΓ genΔ
  surjective := fstHom_surjective genΓ genΔ hgenΓ

def sndQuotient
    (genΓ : ι → Γ) (genΔ : ι → Δ)
    (hgenΔ : IsGenerated genΔ) :
    LabelledGroupQuotient (generator genΓ genΔ) genΔ where
  hom := sndHom genΓ genΔ
  map_gen := sndHom_generator genΓ genΔ
  surjective := sndHom_surjective genΓ genΔ hgenΔ

/-- Finiteness of the common labelled cover, provided both
component groups are finite. No bound on the length of words
representing its elements is claimed. -/
noncomputable instance
    (genΓ : ι → Γ) (genΔ : ι → Δ)
    [Fintype Γ] [Fintype Δ] :
    Fintype (subgroup genΓ genΔ) := by
  classical
  exact Fintype.ofFinite _

end SynchronizedProduct
end ABO
end PSTSEPPA
