import PSTSEPPA.ABO.SynchronizedLabelledGroups
import PSTSEPPA.ABO.StageStabilityWordKernel
import PSTSEPPA.ABO.TransitionGroupGenerated
import PSTSEPPA.ABO.FiniteActionStages

/-!
# Actual rank-k stable synchronized cover from a complete stage

A genuine finite ABO Section-5 cover must not merely consist of a
labelled complete EGraph. It needs an ACTUAL generator-preserving
SURJECTIVE group homomorphism to the ambient group, with the desired
rank-k stability.

Given an ambient E-generated group Γ and ANY complete EGraph T
whose transition words of ambient Γ-value 1 on all ≤k-letter
alphabets are also trivial, synchronize Γ with T's ACTUAL
transition group, generated by the same letters.

The resulting generated subgroup of Γ × Transition(T) projects
onto Γ via a concrete generator-preserving surjective labelled
group quotient (NOT an assumed map). We prove that this
quotient is k-stable by the exact word-kernel characterization.

This is the generic algebraic assembly bridge after the actual
stagewise word kernels. For finite Γ and finite stage carrier,
the synchronized cover is an actually finite group.

Importantly, this is a synchronized cover for a SPECIFIED stage
or stage family; it does not construct the full required finite
ABO Section-5 family Z_k, an H_k-cover, or the reflecting group.
-/

namespace PSTSEPPA
namespace ABO

variable {ι Γ V Edge : Type*}
variable [Fintype ι] [DecidableEq ι] [Group Γ]

namespace CompleteEGraph

variable (T : CompleteEGraph V Edge ι)

/-- A signed word evaluated in the actual transition SUBGROUP
has, after forgetting the subtype, exactly the concrete
complete EGraph's signed word permutation value. -/
theorem evalGroup_transitionSubgroupGenerator_val
    (w : LabelWord ι) :
    ((PSTS.SignedWord.evalGroup T.transitionSubgroupGenerator w :
        T.transitionGroup) : RightPerm V) = T.wordValue w := by
  induction w with
  | nil =>
      rfl
  | cons s w ih =>
      change
        ((PSTS.SignedWord.evalGroupLetter
            T.transitionSubgroupGenerator s :
              T.transitionGroup) : RightPerm V) *
          ((PSTS.SignedWord.evalGroup
            T.transitionSubgroupGenerator w :
              T.transitionGroup) : RightPerm V) =
        T.signedTransition s * T.wordValue w
      rw [T.evalGroupLetter_transitionSubgroup_val, ih]

end CompleteEGraph

namespace SynchronizedProduct

/-- The actual generated synchronous cover of an ambient
labelled group with a complete EGraph's transition SUBGROUP.
This is a subtype of Γ × Transition(T); its generators are
the literal pairs of ambient and stage generators. -/
abbrev stageCover
    (gen : ι → Γ) (T : CompleteEGraph V Edge ι) :=
  subgroup gen T.transitionSubgroupGenerator

/-- Surjective, letter-preserving quotient of the actual
synchronized group onto the ambient Γ. Surjectivity uses
generation of Γ, not any faithfulness of stage actions. -/
def stageCoverQuotient
    (gen : ι → Γ) (T : CompleteEGraph V Edge ι)
    (hgen : IsGenerated gen) :
    LabelledGroupQuotient
      (generator gen T.transitionSubgroupGenerator) gen :=
  fstQuotient gen T.transitionSubgroupGenerator hgen

/-- If the ACTUAL complete stage T kills all Γ-identity
words supported on ≤k letters, its concrete synchronized
cover to Γ is k-stable. The conclusion is a real labelled
surjective group quotient, not a proposed stage map. -/
theorem stageCoverQuotient_kStable_of_stageKernel
    (gen : ι → Γ) (T : CompleteEGraph V Edge ι)
    (hgen : IsGenerated gen)
    (k : ℕ)
    (hkernel :
      ∀ (C : Finset ι), C.card ≤ k →
        ∀ (w : LabelWord ι), LabelWord.Uses C w →
          PSTS.SignedWord.evalGroup gen w = 1 →
            T.wordValue w = 1) :
    (stageCoverQuotient gen T hgen).KStable k := by
  apply (stageCoverQuotient gen T hgen).kStable_of_word_kernel k
  intro C hC w hw hval
  have ht :
      PSTS.SignedWord.evalGroup T.transitionSubgroupGenerator w = 1 := by
    apply Subtype.ext
    exact (T.evalGroup_transitionSubgroupGenerator_val w).trans
      (hkernel C hC w hw hval)
  apply Subtype.ext
  apply Prod.ext
  · change fstHom gen T.transitionSubgroupGenerator
        (PSTS.SignedWord.evalGroup
          (generator gen T.transitionSubgroupGenerator) w) = (1 : Γ)
    exact (fstHom_evalGroup gen T.transitionSubgroupGenerator w).trans hval
  · change sndHom gen T.transitionSubgroupGenerator
        (PSTS.SignedWord.evalGroup
          (generator gen T.transitionSubgroupGenerator) w) =
        (1 : T.transitionGroup)
    exact (sndHom_evalGroup gen T.transitionSubgroupGenerator w).trans ht

/-- For finite ambient Γ and finite stage carrier V,
the ACTUAL synchronized rank-stable candidate group
is finite as a subtype of the product of two finite groups. -/
theorem finite_stageCover
    (gen : ι → Γ) (T : CompleteEGraph V Edge ι)
    [Finite Γ] [Finite V] :
    Finite (stageCover gen T) := by
  classical
  letI : Fintype Γ := Fintype.ofFinite _
  letI : Fintype V := Fintype.ofFinite _
  letI : Fintype T.transitionGroup := inferInstance
  infer_instance

end SynchronizedProduct

end ABO
end PSTSEPPA
