import PSTSEPPA.ABO.SynchronizedLabelledGroups

/-!
# Actual synchronized labelled groups are generated by their letters

A synchronized product is not the entire direct product Γ × Δ:
it is the ACTUAL subgroup generated by pairs of equally labelled
positive generators. The distinguished generator map of this
subgroup is therefore generated, even if neither original
generator family generates its full ambient factor.

This basic structural lemma is necessary to feed a genuinely
constructed finite rank-one group cover into the next
rank-two Cayley/coset-extension stage; it is not permissible
to assume IsGenerated for the intermediate H₁ without proof.

The proof transports a closure induction through the subgroup
subtype. Empty label sets, identical/trivial generators, and
potentially non-surjective original generator families are allowed.
No retractability, stability, or finiteness hypotheses are used.
-/

namespace PSTSEPPA
namespace ABO

variable {ι Γ Δ : Type*} [Fintype ι] [DecidableEq ι]
variable [Group Γ] [Group Δ]

namespace SynchronizedProduct

/-- The TRUE synchronized subgroup is generated by the very
same labelled pairs used to define it, with no extra hypothesis
on either ambient factor. -/
theorem generator_isGenerated
    (genΓ : ι → Γ) (genΔ : ι → Δ) :
    IsGenerated (generator genΓ genΔ) := by
  unfold IsGenerated
  have hLift :
      ∀ (g : Γ × Δ) (hg : g ∈ subgroup genΓ genΔ),
        (⟨g, hg⟩ : subgroup genΓ genΔ) ∈
          Subgroup.closure (Set.range (generator genΓ genΔ)) := by
    intro g hg
    change g ∈ Subgroup.closure
      (Set.range (fun i : ι => (genΓ i, genΔ i))) at hg
    induction hg using Subgroup.closure_induction with
    | mem p hp =>
        obtain ⟨i, rfl⟩ := hp
        exact Subgroup.subset_closure ⟨i, rfl⟩
    | one =>
        exact (Subgroup.closure (Set.range
          (generator genΓ genΔ))).one_mem
    | mul x y hx hy ihx ihy =>
        exact (Subgroup.closure (Set.range
          (generator genΓ genΔ))).mul_mem ihx ihy
    | inv x hx ih =>
        exact (Subgroup.closure (Set.range
          (generator genΓ genΔ))).inv_mem ih
  apply top_unique
  intro g _
  exact hLift g.1 g.2

end SynchronizedProduct
end ABO
end PSTSEPPA
