import PSTSEPPA.ABO.DisjointUnionEGraphs
import Mathlib.Algebra.Group.End

/-!
# Transition group of a disjoint complete E-graph is the synchronized product

This bridges two independently Lean-certified source-facing ABO constructions:

* #257: the synchronized subgroup of the product of two labelled
  groups, generated by equally labelled pairs of generators;
* #260: the LITERAL disjoint union of two complete E-graphs, with
  real signed paths confined to the relevant vertex component.

For complete E-graphs T₁ and T₂, each signed transition permutation
of the disjoint union acts separately in each summand. The transition
group of T₁ ⊔ T₂ is therefore naturally isomorphic to the subgroup
of Transition(T₁) × Transition(T₂) generated by synchronized pairs
(τ₁(i), τ₂(i)).

The proof uses actual opposite-permutation multiplication to match
the chronological word convention and does not assume injective
generator labelling. In particular the result includes loops,
repeated/identity transition generators and empty carriers.

It is a genuine Section 5 finite-stage group identification, not
an assertion of the reflecting group, whole-component cluster
property, bridge-free induction or the corrected Lemma 5.6.
-/

namespace PSTSEPPA
namespace ABO

variable {V₁ E₁ V₂ E₂ ι : Type*}

/-- Disjointly combine two chronological RIGHT permutations.
The opposite convention makes `p*q` mean first p, then q,
exactly as for the complete E-graph transition groups. -/
def rightPermSumHom (V₁ V₂ : Type*) :
    (RightPerm V₁ × RightPerm V₂) →* RightPerm (V₁ ⊕ V₂) where
  toFun p :=
    MulOpposite.op
      (Equiv.Perm.sumCongr (MulOpposite.unop p.1) (MulOpposite.unop p.2))
  map_one' := by
    apply MulOpposite.unop_injective
    change Equiv.Perm.sumCongr
      (1 : Equiv.Perm V₁) (1 : Equiv.Perm V₂) = 1
    exact Equiv.Perm.sumCongr_one
  map_mul' p q := by
    apply MulOpposite.unop_injective
    change
      Equiv.Perm.sumCongr
        (MulOpposite.unop q.1 * MulOpposite.unop p.1)
        (MulOpposite.unop q.2 * MulOpposite.unop p.2) =
      Equiv.Perm.sumCongr (MulOpposite.unop q.1) (MulOpposite.unop q.2) *
        Equiv.Perm.sumCongr (MulOpposite.unop p.1) (MulOpposite.unop p.2)
    exact (Equiv.Perm.sumCongr_mul _ _ _ _).symm

/-- Sum actions determine each coordinate permutation uniquely. -/
theorem rightPermSumHom_injective (V₁ V₂ : Type*) :
    Function.Injective (rightPermSumHom V₁ V₂) := by
  intro p q hpq
  have hSum :
      Equiv.Perm.sumCongr (MulOpposite.unop p.1)
          (MulOpposite.unop p.2) =
        Equiv.Perm.sumCongr (MulOpposite.unop q.1)
          (MulOpposite.unop q.2) :=
    congrArg MulOpposite.unop hpq
  have hProduct :
      (MulOpposite.unop p.1, MulOpposite.unop p.2) =
        (MulOpposite.unop q.1, MulOpposite.unop q.2) :=
    Equiv.Perm.sumCongrHom_injective hSum
  apply Prod.ext
  · apply MulOpposite.unop_injective
    exact congrArg Prod.fst hProduct
  · apply MulOpposite.unop_injective
    exact congrArg Prod.snd hProduct

namespace CompleteEGraph

/-- The sum of both original generator actions is exactly the
literal transition generator of their disjoint E-graph.
This is an identity of RIGHT PERMUTATIONS, not only word endpoints. -/
theorem rightPermSumHom_transitionGenerator
    (G : CompleteEGraph V₁ E₁ ι)
    (H : CompleteEGraph V₂ E₂ ι)
    (i : ι) :
    rightPermSumHom V₁ V₂
        (G.transitionGenerator i, H.transitionGenerator i) =
      (G.disjointUnion H).transitionGenerator i := by
  apply MulOpposite.unop_injective
  apply Equiv.ext
  intro x
  cases x with
  | inl x =>
      have h :=
        G.disjointUnion_followWord_inl H x [PSTS.SignedLetter.pos i]
      change
        (G.disjointUnion H).letterPerm (.pos i) (.inl x) =
          .inl (G.letterPerm (.pos i) x) at h
      change
        (Sum.inl (G.letterPerm (.pos i) x)) =
          (G.disjointUnion H).letterPerm (.pos i) (Sum.inl x)
      exact h.symm
  | inr x =>
      have h :=
        G.disjointUnion_followWord_inr H x [PSTS.SignedLetter.pos i]
      change
        (G.disjointUnion H).letterPerm (.pos i) (.inr x) =
          .inr (H.letterPerm (.pos i) x) at h
      change
        (Sum.inr (H.letterPerm (.pos i) x)) =
          (G.disjointUnion H).letterPerm (.pos i) (Sum.inr x)
      exact h.symm

/-- Every element of the synchronized product of the two
transition groups acts as a transition of the literal disjoint
union. The proof is an actual induction on group generation. -/
theorem rightPermSumHom_mem_transitionGroup
    (G : CompleteEGraph V₁ E₁ ι)
    (H : CompleteEGraph V₂ E₂ ι)
    {g : RightPerm V₁ × RightPerm V₂}
    (hg : g ∈ SynchronizedProduct.subgroup
        G.transitionGenerator H.transitionGenerator) :
    rightPermSumHom V₁ V₂ g ∈
      (G.disjointUnion H).transitionGroup := by
  induction hg using Subgroup.closure_induction with
  | mem x hx =>
      obtain ⟨i, rfl⟩ := hx
      rw [rightPermSumHom_transitionGenerator]
      exact (G.disjointUnion H).transitionGenerator_mem i
  | one =>
      simpa using (G.disjointUnion H).transitionGroup.one_mem
  | mul x y hx hy ihx ihy =>
      rw [map_mul]
      exact (G.disjointUnion H).transitionGroup.mul_mem ihx ihy
  | inv x hx ih =>
      rw [map_inv]
      exact (G.disjointUnion H).transitionGroup.inv_mem ih

/-- The actual homomorphism from the synchronized subgroup to
the transition group of the literal disjoint complete E-graph. -/
noncomputable def synchronizedToDisjointTransition
    (G : CompleteEGraph V₁ E₁ ι)
    (H : CompleteEGraph V₂ E₂ ι) :
    SynchronizedProduct.subgroup
        G.transitionGenerator H.transitionGenerator →*
      (G.disjointUnion H).transitionGroup where
  toFun g :=
    ⟨rightPermSumHom V₁ V₂ g.1,
      G.rightPermSumHom_mem_transitionGroup H g.2⟩
  map_one' := by
    apply Subtype.ext
    exact map_one (rightPermSumHom V₁ V₂)
  map_mul' x y := by
    apply Subtype.ext
    exact map_mul (rightPermSumHom V₁ V₂) x.1 y.1

@[simp]
theorem synchronizedToDisjointTransition_generator
    (G : CompleteEGraph V₁ E₁ ι)
    (H : CompleteEGraph V₂ E₂ ι)
    (i : ι) :
    G.synchronizedToDisjointTransition H
      (SynchronizedProduct.generator
        G.transitionGenerator H.transitionGenerator i) =
      (⟨(G.disjointUnion H).transitionGenerator i,
        (G.disjointUnion H).transitionGenerator_mem i⟩ :
          (G.disjointUnion H).transitionGroup) := by
  apply Subtype.ext
  exact rightPermSumHom_transitionGenerator G H i

/-- The synchronized-to-disjoint transition hom is INJECTIVE:
distinct paired component permutations act differently on
the disjoint union. -/
theorem synchronizedToDisjointTransition_injective
    (G : CompleteEGraph V₁ E₁ ι)
    (H : CompleteEGraph V₂ E₂ ι) :
    Function.Injective (G.synchronizedToDisjointTransition H) := by
  intro p q hpq
  apply Subtype.ext
  exact rightPermSumHom_injective V₁ V₂ (congrArg Subtype.val hpq)

/-- Every transition in the disjoint union is generated by
the synchronized paired transition generators. -/
theorem synchronizedToDisjointTransition_surjective
    (G : CompleteEGraph V₁ E₁ ι)
    (H : CompleteEGraph V₂ E₂ ι) :
    Function.Surjective (G.synchronizedToDisjointTransition H) := by
  have hsur :
      ∀ x : RightPerm (V₁ ⊕ V₂),
        x ∈ (G.disjointUnion H).transitionGroup →
        ∃ g : SynchronizedProduct.subgroup
            G.transitionGenerator H.transitionGenerator,
          rightPermSumHom V₁ V₂ g.1 = x := by
    intro x hx
    induction hx using Subgroup.closure_induction with
    | mem x hx =>
        obtain ⟨i, rfl⟩ := hx
        exact ⟨SynchronizedProduct.generator
          G.transitionGenerator H.transitionGenerator i,
          rightPermSumHom_transitionGenerator G H i⟩
    | one =>
        exact ⟨1, map_one (rightPermSumHom V₁ V₂)⟩
    | mul x y hx hy ihx ihy =>
        obtain ⟨a, ha⟩ := ihx
        obtain ⟨b, hb⟩ := ihy
        refine ⟨a * b, ?_⟩
        calc
          rightPermSumHom V₁ V₂ ((a * b).1) =
              rightPermSumHom V₁ V₂ (a.1 * b.1) := rfl
          _ = rightPermSumHom V₁ V₂ a.1 *
                rightPermSumHom V₁ V₂ b.1 := map_mul _ _ _
          _ = x * y := by rw [ha, hb]
    | inv x hx ih =>
        obtain ⟨a, ha⟩ := ih
        refine ⟨a⁻¹, ?_⟩
        calc
          rightPermSumHom V₁ V₂ ((a⁻¹).1) =
              rightPermSumHom V₁ V₂ (a.1)⁻¹ := by
                change rightPermSumHom V₁ V₂ (a.1⁻¹) =
                  (rightPermSumHom V₁ V₂ a.1)⁻¹
                exact map_inv (rightPermSumHom V₁ V₂) a.1
          _ = x⁻¹ := congrArg Inv.inv ha
  intro x
  obtain ⟨y, hy⟩ := hsur x.1 x.2
  exact ⟨y, Subtype.ext hy⟩

/-- The transition group of a literal disjoint union is
ISOMORPHIC to the synchronized subgroup generated by paired
component transitions. This is the exact algebraic content of
the complete-graph disjoint-union stage in ABO Section 5. -/
noncomputable def synchronizedTransitionEquiv
    (G : CompleteEGraph V₁ E₁ ι)
    (H : CompleteEGraph V₂ E₂ ι) :
    SynchronizedProduct.subgroup
        G.transitionGenerator H.transitionGenerator ≃*
      (G.disjointUnion H).transitionGroup :=
  MulEquiv.ofBijective
    (G.synchronizedToDisjointTransition H)
    ⟨G.synchronizedToDisjointTransition_injective H,
     G.synchronizedToDisjointTransition_surjective H⟩

end CompleteEGraph
end ABO
end PSTSEPPA
