import PSTSEPPA.ABO.Graph
import Mathlib.Algebra.Group.End
import Mathlib.Algebra.Group.Subgroup.Lattice

/-!
# Transition groups of complete ABO graphs

ABO lets words act on vertices on the right.  Mathlib permutation
multiplication is ordinary function composition, so we put permutations in the
opposite group.  With this convention the group product has exactly the same
left-to-right order as concatenation of ABO words.
-/

namespace PSTSEPPA
namespace ABO

abbrev RightPerm (V : Type*) :=
  MulOpposite (Equiv.Perm V)

namespace CompleteEGraph

variable {V Edge ι : Type*} (G : CompleteEGraph V Edge ι)

/-- Permutation induced by one signed label. -/
noncomputable def letterPerm (s : SignedLabel ι) : Equiv.Perm V where
  toFun u := G.target (G.edgeAt u s)
  invFun u :=
    G.target (G.edgeAt u (PSTS.SignedLetter.inv s))
  left_inv u := by
    change
      G.target
          (G.edgeAt (G.target (G.edgeAt u s))
            (PSTS.SignedLetter.inv s)) = u
    rw [G.edgeAt_inv]
    simp [LabelledGraph.target, G.inv_inv]
  right_inv u := by
    change
      G.target
          (G.edgeAt
            (G.target (G.edgeAt u (PSTS.SignedLetter.inv s))) s) = u
    have h := G.edgeAt_inv u (PSTS.SignedLetter.inv s)
    simp only [PSTS.SignedLetter.inv_inv] at h
    rw [h]
    simp [LabelledGraph.target, G.inv_inv]

@[simp]
theorem letterPerm_apply (s : SignedLabel ι) (u : V) :
    G.letterPerm s u = G.target (G.edgeAt u s) :=
  rfl

@[simp]
theorem letterPerm_inv (s : SignedLabel ι) :
    G.letterPerm (PSTS.SignedLetter.inv s) = (G.letterPerm s).symm := by
  cases s <;> rfl

/-- Positive generator of the transition group.  The opposite permutation
group aligns multiplication with the paper's right action convention. -/
noncomputable def transitionGenerator (i : ι) : RightPerm V :=
  MulOpposite.op (G.letterPerm (.pos i))

/-- Signed generator value in the right-permutation group. -/
noncomputable def signedTransition : SignedLabel ι → RightPerm V
  | .pos i => G.transitionGenerator i
  | .neg i => (G.transitionGenerator i)⁻¹

@[simp]
theorem signedTransition_pos (i : ι) :
    G.signedTransition (.pos i) = G.transitionGenerator i :=
  rfl

@[simp]
theorem signedTransition_neg (i : ι) :
    G.signedTransition (.neg i) = (G.transitionGenerator i)⁻¹ :=
  rfl

/-- ABO value of a signed word. -/
noncomputable def wordValue (H : CompleteEGraph V Edge ι) :
    LabelWord ι → RightPerm V
  | [] => 1
  | s :: w => H.signedTransition s * wordValue H w

@[simp]
theorem wordValue_nil :
    G.wordValue ([] : LabelWord ι) = 1 :=
  rfl

@[simp]
theorem wordValue_cons (s : SignedLabel ι) (w : LabelWord ι) :
    G.wordValue (s :: w) = G.signedTransition s * G.wordValue w :=
  rfl

@[simp]
theorem wordValue_append (u v : LabelWord ι) :
    G.wordValue (u ++ v) = G.wordValue u * G.wordValue v := by
  induction u with
  | nil =>
      simp
  | cons s u ih =>
      simp [ih, mul_assoc]

/-- Apply a right-permutation value to a vertex. -/
def rightApply (g : RightPerm V) (u : V) : V :=
  MulOpposite.unop g u

theorem rightApply_mul (g h : RightPerm V) (u : V) :
    rightApply (g * h) u = rightApply h (rightApply g u) := by
  rfl

@[simp]
theorem rightApply_transitionGenerator (i : ι) (u : V) :
    rightApply (G.transitionGenerator i) u =
      G.letterPerm (.pos i) u :=
  rfl

@[simp]
theorem rightApply_signedTransition (s : SignedLabel ι) (u : V) :
    rightApply (G.signedTransition s) u = G.letterPerm s u := by
  cases s with
  | pos i =>
      rfl
  | neg i =>
      change (G.letterPerm (.pos i)).symm u =
        G.letterPerm (.neg i) u
      exact congrArg (fun p : Equiv.Perm V => p u)
        (G.letterPerm_inv (.pos i)).symm

/-- Word values act exactly by following the uniquely labelled path. -/
theorem rightApply_wordValue (w : LabelWord ι) (u : V) :
    rightApply (G.wordValue w) u = G.followWord u w := by
  induction w generalizing u with
  | nil =>
      rfl
  | cons s w ih =>
      rw [wordValue_cons, rightApply_mul, rightApply_signedTransition]
      exact ih (u := G.letterPerm s u)

/-- The transition group, realised as the subgroup of right permutations
generated by the positive labels.  The generator map is intentionally not
assumed injective and may hit the identity. -/
noncomputable def transitionGroup : Subgroup (RightPerm V) :=
  Subgroup.closure (Set.range G.transitionGenerator)

theorem transitionGenerator_mem (i : ι) :
    G.transitionGenerator i ∈ G.transitionGroup :=
  Subgroup.subset_closure ⟨i, rfl⟩

theorem signedTransition_mem (s : SignedLabel ι) :
    G.signedTransition s ∈ G.transitionGroup := by
  cases s with
  | pos i =>
      exact G.transitionGenerator_mem i
  | neg i =>
      exact (G.transitionGroup).inv_mem (G.transitionGenerator_mem i)

/-- Every signed word evaluates inside the transition group. -/
theorem wordValue_mem (w : LabelWord ι) :
    G.wordValue w ∈ G.transitionGroup := by
  induction w with
  | nil =>
      exact (G.transitionGroup).one_mem
  | cons s w ih =>
      exact (G.transitionGroup).mul_mem (G.signedTransition_mem s) ih

/-- Inverting a signed letter inverts its transition value. -/
@[simp]
theorem signedTransition_inv (s : SignedLabel ι) :
    G.signedTransition (PSTS.SignedLetter.inv s) =
      (G.signedTransition s)⁻¹ := by
  cases s <;> simp [signedTransition]

/-- Formal inversion of words agrees with inversion in the transition group. -/
@[simp]
theorem wordValue_inv (w : LabelWord ι) :
    G.wordValue (PSTS.SignedWord.inv w) = (G.wordValue w)⁻¹ := by
  induction w with
  | nil =>
      simp [wordValue, PSTS.SignedWord.inv]
  | cons s w ih =>
      rw [PSTS.SignedWord.inv_cons, wordValue_append, ih]
      simp [wordValue, signedTransition_inv]

/-- Every element of the transition group is the value of some signed word.

This is the algebraic surjectivity needed for the canonical Cayley-to-component
map; it uses no faithfulness of the generator labelling. -/
theorem exists_wordValue_eq {g : RightPerm V}
    (hg : g ∈ G.transitionGroup) :
    ∃ w : LabelWord ι, G.wordValue w = g := by
  change g ∈ Subgroup.closure (Set.range G.transitionGenerator) at hg
  induction hg using Subgroup.closure_induction with
  | mem x hx =>
      rcases hx with ⟨i, rfl⟩
      exact ⟨[PSTS.SignedLetter.pos i], by simp [wordValue]⟩
  | one =>
      exact ⟨[], rfl⟩
  | mul x y hx hy ihx ihy =>
      rcases ihx with ⟨u, hu⟩
      rcases ihy with ⟨v, hv⟩
      exact ⟨u ++ v, by rw [wordValue_append, hu, hv]⟩
  | inv x hx ih =>
      rcases ih with ⟨w, hw⟩
      exact ⟨PSTS.SignedWord.inv w, by rw [wordValue_inv, hw]⟩


end CompleteEGraph

end ABO
end PSTSEPPA
