import PSTSEPPA.ABO.CanonicalCover
import PSTSEPPA.ABO.Retractability

/-!
# Transition groups are generated by their actual labelled stage generators

The synchronized-product stability theorem works with labelled
groups generated by their distinguished letters. For the actual
transition group of ANY complete E-graph, this is a theorem,
not a hypothesis: its underlying right-permutation subgroup is
defined as the closure of the transition generators.

We transport the subgroup generation induction through the
transition-subgroup subtype, producing the source-facing
IsGenerated statement directly. This does not require that
the labelled transitions are distinct or nonidentity and
works for empty vertex or letter carriers.
-/

namespace PSTSEPPA
namespace ABO

namespace CompleteEGraph

variable {V Edge ι : Type*} [Fintype ι] [DecidableEq ι]
variable (T : CompleteEGraph V Edge ι)

/-- The actual transition group of a complete E-graph is
generated by the same-labelled transition generators when
regarded as elements of the subgroup. No freeness assumption
is made on labels or on the action. -/
theorem transitionSubgroupGenerator_isGenerated :
    IsGenerated T.transitionSubgroupGenerator := by
  unfold IsGenerated
  have hLift :
      ∀ (g : RightPerm V) (hg : g ∈ T.transitionGroup),
        (⟨g, hg⟩ : T.transitionGroup) ∈
          Subgroup.closure (Set.range T.transitionSubgroupGenerator) := by
    intro g hg
    change g ∈ Subgroup.closure (Set.range T.transitionGenerator) at hg
    induction hg using Subgroup.closure_induction with
    | mem p hp =>
        obtain ⟨i, rfl⟩ := hp
        exact Subgroup.subset_closure ⟨i, rfl⟩
    | one =>
        exact (Subgroup.closure (Set.range T.transitionSubgroupGenerator)).one_mem
    | mul x y hx hy ihx ihy =>
        exact (Subgroup.closure (Set.range T.transitionSubgroupGenerator)).mul_mem
          ihx ihy
    | inv x hx ih =>
        exact (Subgroup.closure (Set.range T.transitionSubgroupGenerator)).inv_mem ih
  apply top_unique
  intro g _
  exact hLift g.1 g.2

end CompleteEGraph
end ABO
end PSTSEPPA
