import PSTSEPPA.ABO.UnaryDetectorGroup
import PSTSEPPA.ABO.RankTwoLocalThreeFamilyCover
import PSTSEPPA.ABO.KRetractableCosetIntersections
import PSTSEPPA.ABO.SynchronizedLabelledGroups
import PSTSEPPA.ABO.StageStabilityWordKernel
import PSTSEPPA.ABO.StabilityRetractability

/-!
# A finite one-stable and two-retractable H₁-like group above any generated Γ

This is a concrete algebraic candidate for the corrected ABO Theorem-3.8
rank-one BASE. Given a generated labelled group Γ, let
  D = Π_i Γ[{i}]
be its true unary detector group, with label j acting only in
coordinate j. D is globally retractable (proved in UnaryDetectorGroup).

We take the ACTUAL generated subgroup D₀ of D, retaining the generator
map with outside-universe letters trivially completed; the map is
surjective onto D₀ by construction. Synchronize Γ with D₀, obtaining
a real group H generated by the pairs of corresponding labels.

We show two honest generator-preserving SURJECTIVE labelled quotients:
  H ↠ Γ  and  H ↠ D₀.
BOTH quotients are 1-stable because the value of any singleton-word
is faithfully detected by its own cyclic coordinate in D.
Since D₀ is globally retractable, the already certified corrected
ABO rank-descent theorem implies H is 2-retractable. For finite Γ,
both detector factors and H are finite.

This does NOT yet build the extra Y₁-Cayley-cover actions or the
specific source H₁ as defined by Theorem 3.8. It is a strong
conditional algebraic H₁-base alternative, not a claim to have
completed the source Section-5 tower or PSTS EPPA.
-/

namespace PSTSEPPA
namespace ABO

variable {ι Γ : Type*} [Fintype ι] [DecidableEq ι] [Group Γ]

/-- The genuine subgroup of the detector product generated by ALL
positive detector letters. No claim that the larger product has
been shown generated by them is needed. -/
abbrev UnaryGeneratedDetectorGroup (gen : ι → Γ) :=
  generatedSubgroup (unaryDetectorGenerator gen) (Finset.univ : Finset ι)

/-- Its own actual labelled generator map (every label lies in univ). -/
def unaryGeneratedDetectorGenerator (gen : ι → Γ) :
    ι → UnaryGeneratedDetectorGroup gen :=
  trivialCompletionGenerator (unaryDetectorGenerator gen) Finset.univ

/-- All its elements are signed words in the detector generators,
by the certified generated-subalphabet lemma. -/
theorem isGenerated_unaryGeneratedDetectorGenerator
    (gen : ι → Γ) :
    IsGenerated (unaryGeneratedDetectorGenerator gen) :=
  isGenerated_trivialCompletionGenerator
    (unaryDetectorGenerator gen) Finset.univ

/-- Word evaluation in the generated detector subgroup, coerced
into the full product, is EXACTLY the same full detector word. -/
theorem coe_evalGroup_unaryGeneratedDetector
    (gen : ι → Γ) (w : LabelWord ι) :
    ((PSTS.SignedWord.evalGroup
       (unaryGeneratedDetectorGenerator gen) w :
          UnaryGeneratedDetectorGroup gen) : UnaryDetectorGroup gen) =
      PSTS.SignedWord.evalGroup (unaryDetectorGenerator gen) w := by
  change
    ((PSTS.SignedWord.evalGroup
      (trivialCompletionGenerator (unaryDetectorGenerator gen) Finset.univ) w :
        generatedSubgroup (unaryDetectorGenerator gen) Finset.univ) :
      UnaryDetectorGroup gen) =
        PSTS.SignedWord.evalGroup (unaryDetectorGenerator gen) w
  rw [coe_evalGroup_trivialCompletionGenerator,
    LabelWord.restrictTo_univ]

/-- Even without global retractability of Γ, the ACTUAL generated
unary-detector subgroup has a globally retractable generator map. -/
theorem retractable_unaryGeneratedDetectorGenerator
    (gen : ι → Γ) :
    Retractable (unaryGeneratedDetectorGenerator gen) := by
  apply retractable_trivialCompletionGenerator_of_kRetractable
    (unaryDetectorGenerator gen) (Fintype.card ι)
    (kRetractable_of_retractable (unaryDetectorGenerator gen)
      (retractable_unaryDetectorGenerator gen) (Fintype.card ι))
    Finset.univ
  simp

/-- Any Γ-relation on at most ONE unsigned generator vanishes
in the full detector product, including inverse letters and
trivial/repeated generators. This direction uses only the automatic
rank-one retractability of Γ and actual word restriction. -/
theorem unaryDetector_word_eq_one_of_ambient
    (gen : ι → Γ)
    (C : Finset ι) (hC : C.card ≤ 1)
    (w : LabelWord ι) (hw : LabelWord.Uses C w)
    (hval : PSTS.SignedWord.evalGroup gen w = 1) :
    PSTS.SignedWord.evalGroup (unaryDetectorGenerator gen) w = 1 := by
  apply funext
  intro i
  change
    (PSTS.SignedWord.evalGroup (unaryDetectorGenerator gen) w) i = 1
  have hEq :
      PSTS.SignedWord.evalGroup gen w =
        PSTS.SignedWord.evalGroup gen ([] : LabelWord ι) := by
    simpa using hval
  have hRestrict :=
    KRetractable.restrictTo_eq_of_uses
      gen (kRetractable_one gen) C hC ({i} : Finset ι)
      w [] hw (LabelWord.uses_nil C) hEq
  have hNil : LabelWord.restrictTo ({i} : Finset ι)
      ([] : LabelWord ι) = [] := rfl
  rw [hNil] at hRestrict
  have hCoord :
      PSTS.SignedWord.evalGroup
        (trivialCompletionGenerator gen ({i} : Finset ι)) w = 1 := by
    apply Subtype.ext
    change
      ((PSTS.SignedWord.evalGroup
        (trivialCompletionGenerator gen ({i} : Finset ι)) w :
            generatedSubgroup gen {i}) : Γ) = 1
    rw [coe_evalGroup_trivialCompletionGenerator]
    simpa using hRestrict
  exact (evalGroup_unaryDetector_apply gen w i).trans hCoord

/-- Conversely, a word on at most ONE label is trivial in Γ
whenever its exact detector word value is trivial. The coordinate
belonging to that label embeds the actual cyclic subgroup Γ[{i}]
back into Γ, so no exponent-order information is lost. -/
theorem ambient_word_eq_one_of_unaryDetector
    (gen : ι → Γ)
    (C : Finset ι) (hC : C.card ≤ 1)
    (w : LabelWord ι) (hw : LabelWord.Uses C w)
    (hdet :
      PSTS.SignedWord.evalGroup (unaryDetectorGenerator gen) w = 1) :
    PSTS.SignedWord.evalGroup gen w = 1 := by
  by_cases hEmpty : C = ∅
  · have hwNil : w = [] := by
      cases w with
      | nil => rfl
      | cons s w =>
          have hs : signedBase s ∈ C := hw.1
          simp [hEmpty] at hs
    simp [hwNil]
  · have hNonempty : C.Nonempty :=
      Finset.nonempty_iff_ne_empty.mpr hEmpty
    obtain ⟨i, hi⟩ := hNonempty
    have hCi : C ⊆ ({i} : Finset ι) := by
      intro j hj
      have hji : j = i := (Finset.card_le_one.mp hC) j hj i hi
      simpa [hji]
    have hwI : LabelWord.Uses ({i} : Finset ι) w :=
      LabelWord.Uses.mono_explicit C ({i} : Finset ι) hCi w hw
    have hCoord :
        PSTS.SignedWord.evalGroup
          (trivialCompletionGenerator gen ({i} : Finset ι)) w = 1 := by
      have hAt := congrArg
        (fun x : UnaryDetectorGroup gen => x i) hdet
      change PSTS.SignedWord.evalGroup
        (trivialCompletionGenerator gen ({i} : Finset ι)) w = 1 at hAt
      exact hAt
    have hCoe := congrArg
      (fun x : generatedSubgroup gen {i} => (x : Γ)) hCoord
    rw [coe_evalGroup_trivialCompletionGenerator,
      LabelWord.restrictTo_eq_self_of_uses
        ({i} : Finset ι) w hwI] at hCoe
    simpa using hCoe

/-- The true generated subgroup of Γ × D₀, with synchronized
positive labels. -/
abbrev UnarySynchronizedCover (gen : ι → Γ) :=
  SynchronizedProduct.subgroup gen (unaryGeneratedDetectorGenerator gen)

/-- The first coordinate gives a genuine generated labelled
surjection onto Γ. -/
def unarySynchronizedCoverQuotient
    (gen : ι → Γ) (hgen : IsGenerated gen) :
    LabelledGroupQuotient
      (SynchronizedProduct.generator gen
        (unaryGeneratedDetectorGenerator gen)) gen :=
  SynchronizedProduct.fstQuotient gen
    (unaryGeneratedDetectorGenerator gen) hgen

/-- The second coordinate is also surjective, onto the ACTUAL
generated detector subgroup D₀. -/
def unarySynchronizedDetectorQuotient
    (gen : ι → Γ) :
    LabelledGroupQuotient
      (SynchronizedProduct.generator gen
        (unaryGeneratedDetectorGenerator gen))
      (unaryGeneratedDetectorGenerator gen) :=
  SynchronizedProduct.sndQuotient gen
    (unaryGeneratedDetectorGenerator gen)
    (isGenerated_unaryGeneratedDetectorGenerator gen)

/-- Genuine rank-one stability of H ↠ Γ. The unary detector
coordinates vanish on every ambient one-letter group relation. -/
theorem unarySynchronizedCoverQuotient_oneStable
    (gen : ι → Γ) (hgen : IsGenerated gen) :
    (unarySynchronizedCoverQuotient gen hgen).KStable 1 := by
  apply (unarySynchronizedCoverQuotient gen hgen).kStable_of_word_kernel 1
  intro C hC w hw hval
  have hDetector :
      PSTS.SignedWord.evalGroup
        (unaryGeneratedDetectorGenerator gen) w = 1 := by
    apply Subtype.ext
    change
      ((PSTS.SignedWord.evalGroup
        (unaryGeneratedDetectorGenerator gen) w :
          UnaryGeneratedDetectorGroup gen) : UnaryDetectorGroup gen) = 1
    rw [coe_evalGroup_unaryGeneratedDetector]
    exact unaryDetector_word_eq_one_of_ambient gen C hC w hw hval
  apply Subtype.ext
  apply Prod.ext
  · change SynchronizedProduct.fstHom gen
        (unaryGeneratedDetectorGenerator gen)
        (PSTS.SignedWord.evalGroup
          (SynchronizedProduct.generator gen
            (unaryGeneratedDetectorGenerator gen)) w) = (1 : Γ)
    exact (SynchronizedProduct.fstHom_evalGroup gen
      (unaryGeneratedDetectorGenerator gen) w).trans hval
  · change SynchronizedProduct.sndHom gen
        (unaryGeneratedDetectorGenerator gen)
        (PSTS.SignedWord.evalGroup
          (SynchronizedProduct.generator gen
            (unaryGeneratedDetectorGenerator gen)) w) =
              (1 : UnaryGeneratedDetectorGroup gen)
    exact (SynchronizedProduct.sndHom_evalGroup gen
      (unaryGeneratedDetectorGenerator gen) w).trans hDetector

/-- Genuine rank-one stability of the OTHER quotient H ↠ D₀.
A detector one-letter relation already holds in the ambient Γ. -/
theorem unarySynchronizedDetectorQuotient_oneStable
    (gen : ι → Γ) :
    (unarySynchronizedDetectorQuotient gen).KStable 1 := by
  apply (unarySynchronizedDetectorQuotient gen).kStable_of_word_kernel 1
  intro C hC w hw hval
  have hFull :
      PSTS.SignedWord.evalGroup (unaryDetectorGenerator gen) w = 1 := by
    have h := congrArg
      (fun x : UnaryGeneratedDetectorGroup gen =>
        (x : UnaryDetectorGroup gen)) hval
    change PSTS.SignedWord.evalGroup (unaryDetectorGenerator gen) w = 1 at h
    exact h
  have hAmbient :
      PSTS.SignedWord.evalGroup gen w = 1 :=
    ambient_word_eq_one_of_unaryDetector gen C hC w hw hFull
  apply Subtype.ext
  apply Prod.ext
  · change SynchronizedProduct.fstHom gen
        (unaryGeneratedDetectorGenerator gen)
        (PSTS.SignedWord.evalGroup
          (SynchronizedProduct.generator gen
            (unaryGeneratedDetectorGenerator gen)) w) = (1 : Γ)
    exact (SynchronizedProduct.fstHom_evalGroup gen
      (unaryGeneratedDetectorGenerator gen) w).trans hAmbient
  · change SynchronizedProduct.sndHom gen
        (unaryGeneratedDetectorGenerator gen)
        (PSTS.SignedWord.evalGroup
          (SynchronizedProduct.generator gen
            (unaryGeneratedDetectorGenerator gen)) w) =
              (1 : UnaryGeneratedDetectorGroup gen)
    exact (SynchronizedProduct.sndHom_evalGroup gen
      (unaryGeneratedDetectorGenerator gen) w).trans hval

/-- The concrete H is TWO-retractable even when the original
ambient Γ is not. This is corrected ABO R1 applied to its
1-stable quotient onto the globally retractable detector D₀. -/
theorem unarySynchronizedCover_twoRetractable
    (gen : ι → Γ) :
    KRetractable
      (SynchronizedProduct.generator gen
        (unaryGeneratedDetectorGenerator gen))
      2 := by
  have hDown : KRetractable (unaryGeneratedDetectorGenerator gen) (1 + 1) :=
    kRetractable_of_retractable _
      (retractable_unaryGeneratedDetectorGenerator gen) (1 + 1)
  have hUp :=
    (unarySynchronizedDetectorQuotient gen).kRetractable_of_kStable
      1 (unarySynchronizedDetectorQuotient_oneStable gen) hDown
  simpa using hUp

variable [Finite Γ]

/-- The concrete synchronized group H is FINITE for finite Γ
and finite label alphabet, independently of any group equations. -/
theorem finite_unarySynchronizedCover
    (gen : ι → Γ) :
    Finite (UnarySynchronizedCover gen) := by
  classical
  letI : Finite (UnaryDetectorGroup gen) :=
    finite_unaryDetectorGroup gen
  letI : Fintype Γ := Fintype.ofFinite _
  letI : Fintype (UnaryDetectorGroup gen) := Fintype.ofFinite _
  letI : Fintype (UnaryGeneratedDetectorGroup gen) := Fintype.ofFinite _
  infer_instance

end ABO
end PSTSEPPA
